import { stagger } from './_bind.js';
const tabs = [...document.querySelectorAll('.sample')]; const doc = document.querySelector('.doc'); const flds = [...document.querySelectorAll('.fld')]; const drop = document.querySelector('.drop'); const hold = document.querySelector('[style*="background: #FDECEA; padding: 10px 12px"]'); const hdr = flds[0]?.parentElement?.querySelector('[style*="font-weight: 600"]'); const hdrTag = flds[0]?.parentElement?.querySelector('.tag');
const S = {
 'Supplier invoice': { doc: doc?.innerHTML, head: 'Extracted → matched against PO-4471', tag: ['r', '1 exception'], f: null, hold: hold?.innerHTML },
 'Buyer PO': { doc: `<div class="dl"><div style="font-weight: 700; color: #1B1B1B; font-size: 12px;">NORDIC RETAIL GROUP AB</div><div>PURCHASE ORDER</div></div><div class="dl"><div>PO no. <span class="hl">NR-4488</span></div><div>Date <span class="hl">15-09-2026</span></div></div><div class="dl"><div>Supplier: Arasu Knits, Tiruppur</div><div>Season <span class="hl">AW26</span></div></div><div style="border-top: 1px solid #ECEBE5; margin: 4px 0;"></div><div class="dl"><div>Style <span class="hl">631KX</span> · Boys hoodie, 280 gsm</div><div><span class="hl">9,600 pcs</span></div></div><div class="dl"><div>Sizes 104–140 · ratio 1:2:3:3:2:1</div><div>FOB <span class="hl">USD 6.40</span></div></div><div class="dl"><div>Delivery <span class="hl">28 Nov 2026</span> · Gothenburg</div><div>Incoterm FOB Tuticorin</div></div><div class="dl" style="font-weight: 700; color: #1B1B1B;"><div>Total</div><div><span class="hl g">USD 61,440.00</span></div></div><div style="margin-top: 6px; color: #7A7975;">Tech pack: 631KX_AW26_v2.pdf attached · Payment: 60 days from BL</div>`,
   head: 'Extracted → new order created', tag: ['g', 'No exceptions'], f: [['Buyer', 'Nordic Retail Group AB · known buyer', '99%'], ['PO', 'NR-4488 · 15 Sep 2026 · AW26', '99%'], ['Style', '631KX · new style → created, tech pack attached', 'new'], ['Item', 'Boys hoodie 280 gsm · 9,600 pcs · 6-size ratio', '98%'], ['Price', 'USD 6.40 FOB · margin vs factory quote: <b>awaiting quote</b>', '97%'], ['ETD', '28 Nov 2026 → T&A generated, 28 stages back-scheduled', 'ok'], ['Terms', '60 days from BL · FOB Tuticorin', 'ok'], ['Tasks', 'Quote request to Koso Tex drafted · 48-h pricing clock started', 'ok']],
   hold: `<div style="font-weight: 600; color: #2E7D4F;">Posted — order 4488 created, T&A generated, pricing clock started.</div><div style="color: #4A4A47;">Nothing needed a human. The merchandiser sees it in the morning digest.</div>` },
 'Delivery note': { doc: `<div class="dl"><div style="font-weight: 700; color: #1B1B1B; font-size: 12px;">SHARMA TRANSPORT CO.</div><div>DELIVERY NOTE / LR</div></div><div class="dl"><div>LR no. <span class="hl">44821</span></div><div>Date <span class="hl">16-09-2026</span></div></div><div class="dl"><div>From: Deccan Polymers, Pune</div><div>To: Arasu Knits, Unit 2</div></div><div style="border-top: 1px solid #ECEBE5; margin: 4px 0;"></div><div class="dl"><div><span class="hl">ABS granules · 25 kg bags</span></div><div><span class="hl">78 bags</span></div></div><div class="dl"><div>Invoice ref <span class="hl">DP/26-27/1183</span></div><div>Vehicle MH12 KX 4471</div></div><div class="dl"><div>Received by: <span class="hl">R. Kumar</span> (signed, photo)</div><div>Condition: 2 bags torn</div></div><div style="margin-top: 6px; color: #7A7975;">Photo of the LR taken on WhatsApp by the storekeeper · 10:42</div>`,
   head: 'Extracted → GRN created against invoice DP/26-27/1183', tag: ['r', '1 exception'], f: [['Document', 'Delivery note / LR 44821 · photo, WhatsApp', '96%'], ['Transporter', 'Sharma Transport · vehicle MH12 KX 4471', '95%'], ['Invoice match', 'DP/26-27/1183 · 80 bags invoiced', 'match'], ['Quantity', '<b>78 bags received</b> vs 80 invoiced · 2 torn', 'short'], ['GRN', 'GRN 4471 created · 1,960 kg into bin D-04', 'ok'], ['Condition', '2 bags torn → damage claim drafted with the photo', 'flag'], ['Signed by', 'R. Kumar · storekeeper', '92%'], ['Posted', 'Stock updated; invoice held for 40-kg short receipt', 'ok']],
   hold: `<div style="font-weight: 600;">Held — 2 bags short and 2 torn; damage claim drafted to Deccan Polymers with the photo.</div><div style="color: #4A4A47;">Stock is updated for what arrived; the invoice waits for the short-receipt to be settled.</div>` }
};
const orig = flds.map(f => f.innerHTML);
function show(name) {
  tabs.forEach(t => { const on = t.textContent.trim() === name; t.classList.toggle('on', on); t.style.color = on ? '' : '#EFEEE9'; });
  const s = S[name]; if (!s) return; doc.innerHTML = s.doc; if (hdr) hdr.textContent = s.head; if (hdrTag) { hdrTag.className = 'tag ' + s.tag[0]; hdrTag.textContent = s.tag[1]; }
  flds.forEach((f, i) => { if (s.f) { const [k, v, c] = s.f[i] || ['', '', '']; f.innerHTML = `<div class="k">${k}</div><div>${v}</div><div class="c">${c}</div>`; f.classList.toggle('bad', /short|mismatch|flag/.test(c)); } else { f.innerHTML = orig[i]; f.classList.toggle('bad', i === 5); } });
  if (hold) hold.innerHTML = s.hold; stagger([...doc.querySelectorAll('.hl')], 140); stagger(flds, 180);
}
tabs.forEach(t => { t.setAttribute('role', 'button'); t.tabIndex = 0; t.style.cursor = 'pointer'; t.addEventListener('click', () => show(t.textContent.trim())); });
if (drop) { drop.setAttribute('role', 'button'); drop.tabIndex = 0; const inp = document.createElement('input'); inp.type = 'file'; inp.accept = '.pdf,image/*'; inp.hidden = true; drop.appendChild(inp);
  drop.addEventListener('click', () => inp.click()); ['dragover', 'dragenter'].forEach(e => drop.addEventListener(e, ev => { ev.preventDefault(); drop.style.borderColor = '#D93A2B'; })); ['dragleave', 'drop'].forEach(e => drop.addEventListener(e, () => drop.style.borderColor = ''));
  const got = f => { drop.firstChild.nextSibling && (drop.lastChild.previousSibling.textContent = ''); drop.querySelector('div + *') ; drop.childNodes[1].textContent = ` ${f.name} — nothing is uploaded from this page. Live extraction on your own documents runs on the demo call; here's how it reads a sample.`; show('Supplier invoice'); };
  inp.addEventListener('change', () => inp.files[0] && got(inp.files[0])); drop.addEventListener('drop', ev => { ev.preventDefault(); ev.dataTransfer.files[0] && got(ev.dataTransfer.files[0]); }); }
