const bins = [...document.querySelectorAll('.bin')]; const panel = document.querySelector('.kv')?.parentElement; const status = document.querySelector('.mono[style*="color: #8E8D87"]');
const DATA = {
 dead: [['ABS granules, black', '1,840 kg · 46 bags · lot L-2024-0913', '₹3.42 L at ₹186/kg', 'Issued 22 kg to moulding · 31 Jul 2025', 'Product line discontinued Aug 2025; no BOM consumes this grade', 'Offer to the sister plant (uses the same grade) or sell to the granule trader at ₹150/kg — <b>recover ₹2.7–3.4 L</b>', 'Idle 412 days'],
        ['Polycarbonate sheet, 3 mm', '312 sheets · lot L-2023-1140', '₹1.86 L at ₹596/sheet', 'Issued 40 to visor line · 04 Mar 2025', 'Visor spec changed to 2.5 mm; 3 mm no longer in any BOM', 'Return to supplier under the annual contract clause, or sell to the fabricator in Chakan — <b>recover ₹1.2–1.6 L</b>', 'Idle 561 days'],
        ['Nylon strap webbing, 25 mm, orange', '2,100 m · lot L-2024-0442', '₹0.63 L at ₹30/m', 'Issued 150 m to harness line · 19 Jun 2025', 'Customer switched to black webbing; orange kept for one export SKU now dormant', 'Use in the next orange harness run (quoted, not yet won) or convert to lanyards — <b>recover ₹0.4–0.6 L</b>', 'Idle 454 days']],
 low: [['Suspension &amp; strap set, helmet', '380 sets · reorder point 1,200', '₹0.12 L', 'Issued 640 today · work order 2410', 'Consumption up 30% since the rail order; reorder point not yet re-set', 'Reorder 4,000 sets now — supplier lead time 9 days, stock-out in 4. <b>Buyer nudged on WhatsApp</b>', 'Below reorder'],
       ['ABS granules, yellow', '210 kg · reorder point 600', '₹0.39 L', 'Issued 180 kg · work order 2398', 'Yellow helmets on two open orders this month', 'Reorder 1,500 kg — 6-day lead time. <b>PO drafted for approval</b>', 'Below reorder'],
       ['Packing cartons, 5-ply, size C', '140 · reorder point 500', '₹0.04 L', 'Issued 220 · dispatch 4471', 'Dispatch volume up; cartons ordered monthly by habit', 'Reorder 2,000 — local supplier, 2 days. <b>Auto-ordered under threshold rule</b>', 'Below reorder']],
 ok: ['Normal · moving stock', 'Within reorder band; last counted this cycle, no variance']
};
if (bins.length && panel) {
  const kv = [...panel.querySelectorAll('.kv')]; const head = panel.querySelector('[style*="font-weight: 600"]'); const tag = panel.querySelector('.tag'); const mv = panel.querySelector('.mv')?.parentElement; let di = 0, li = 0;
  bins.forEach(b => { b.setAttribute('role', 'button'); b.tabIndex = 0; b.style.cursor = 'pointer';
    const pick = () => { bins.forEach(x => x.classList.remove('sel')); b.classList.add('sel'); const id = b.firstElementChild.textContent; if (status) status.textContent = `Bin ${id} selected`;
      if (b.classList.contains('dead')) { const d = DATA.dead[di++ % 3]; head.textContent = `Bin ${id} · ${d[0].replace('&amp;', '&')}`; tag.className = 'tag r'; tag.textContent = d[6]; [d[1], d[2], d[3], d[4], d[5]].forEach((v, i) => kv[i] && (kv[i].lastElementChild.innerHTML = i === 0 ? `<b>${v}</b>` : v)); kv[0].firstElementChild.textContent = 'On hand'; kv[3].firstElementChild.textContent = "Why it's stuck"; kv[4].firstElementChild.textContent = 'AI suggests'; mv && (mv.style.display = ''); }
      else if (b.classList.contains('low')) { const d = DATA.low[li++ % 3]; head.innerHTML = `Bin ${id} · ${d[0]}`; tag.className = 'tag'; tag.style.cssText = 'background:#FFF6E5;color:#B26A00'; tag.textContent = d[6]; [d[1], d[2], d[3], d[4], d[5]].forEach((v, i) => kv[i] && (kv[i].lastElementChild.innerHTML = i === 0 ? `<b>${v}</b>` : v)); kv[3].firstElementChild.textContent = 'Why it\'s low'; kv[4].firstElementChild.textContent = 'AI suggests'; mv && (mv.style.display = 'none'); }
      else { head.textContent = `Bin ${id} · ${DATA.ok[0]}`; tag.className = 'tag g'; tag.style.cssText = ''; tag.textContent = 'OK'; const fill = b.querySelector('.f i').style.width; [`<b>${fill} full</b> · counted this cycle`, 'Within band', 'Issued this week', DATA.ok[1], 'Nothing to do — this is what most bins look like'].forEach((v, i) => kv[i] && (kv[i].lastElementChild.innerHTML = v)); kv[3].firstElementChild.textContent = 'Status'; kv[4].firstElementChild.textContent = 'AI suggests'; mv && (mv.style.display = 'none'); }
      panel.classList.remove('reveal'); void panel.offsetWidth; panel.classList.add('reveal'); };
    b.addEventListener('click', pick); b.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); pick(); } });
  });
}
