const outs = [...document.querySelectorAll('.out')]; const dg = document.querySelector('.dg'); const gv = [...document.querySelectorAll('.gv')].slice(1); const status = document.querySelector('.mono[style*="color: #8E8D87"]');
const D = {
 'Cantonment': { s: 72, d: 'Five outlets normal. <b>Cantonment scored 72</b> — billing variance ₹4,100 on two shifts, one guest complaint (billing). Hygiene and wastage normal.', g: [['Billing variance > ₹2,000 · Cantonment', '<b>Cashier lead Prakash</b> — "Which bills were voided and why?" · void log attached', 'Today 12:00', 'r'], ['Guest complaint (billing) · Cantonment', '<b>Outlet manager Devi</b> — call the guest back; log outcome', 'Today', 'r'], ['Punctuality 3-day trend · Central bus stand', '<b>HR</b> — roster review; not yet a breach', 'Watch', 'k']] },
 'Thillai Nagar': { s: 68, d: 'Five outlets normal. <b>Thillai Nagar scored 68</b> — staff punctuality 4 late arrivals, wastage 6.1% (limit 5%). No complaints.', g: [['Wastage > 5% · Thillai Nagar', '<b>Outlet manager Senthil</b> — "What was wasted and why?" · wastage log photo required', 'Today 12:00', 'r'], ['Late arrivals ≥ 3 · Thillai Nagar', '<b>HR</b> — roster and biometric check', 'Today', 'r'], ['Punctuality 3-day trend · Central bus stand', '<b>HR</b> — roster review; not yet a breach', 'Watch', 'k']] },
 'Srirangam': { s: 61, d: 'Five outlets normal. <b>Srirangam scored 61</b> — wastage 9.4% (limit 5%), hygiene checklist 7 of 12 done, two guest complaints about wait time. Billing variance normal. Central bus stand punctuality slipping for the third day.', g: [['Wastage > 5% two days running · Srirangam', '<b>Outlet manager Ramesh</b> — "What was wasted and why?" · photo of the wastage log required', 'Today 12:00', 'r'], ['Hygiene checklist < 10/12 · Srirangam', '<b>Area supervisor Lakshmi</b> — surprise visit scheduled; checklist re-done on site', 'Today', 'r'], ['Punctuality 3-day trend · Central bus stand', '<b>HR</b> — roster review; not yet a breach', 'Watch', 'k']] },
 'Woraiyur': { s: 66, d: 'Five outlets normal. <b>Woraiyur scored 66</b> — three guest complaints (cold food), kitchen temperature log missing two entries. Wastage normal.', g: [['Complaints ≥ 3 · Woraiyur', '<b>Outlet manager Anand</b> — "What changed in the kitchen line today?" · call each guest back', 'Today 12:00', 'r'], ['Temperature log gaps · Woraiyur', '<b>Area supervisor Lakshmi</b> — verify the log on site tomorrow', 'Tomorrow', 'r'], ['Punctuality 3-day trend · Central bus stand', '<b>HR</b> — roster review; not yet a breach', 'Watch', 'k']] },
 'Central bus stand': { s: 58, d: 'Five outlets normal. <b>Central bus stand scored 58</b> — punctuality now a breach (four days), billing variance ₹6,300, hygiene 9 of 12. Two complaints.', g: [['Punctuality breach · 4 days · Central bus stand', '<b>HR + outlet manager Kumar</b> — roster rebuilt this week; written explanation', 'Today', 'r'], ['Billing variance > ₹2,000 · Central bus stand', '<b>Cashier lead</b> — void log and CCTV clip for the two shifts', 'Today 12:00', 'r'], ['Hygiene 9/12 · Central bus stand', '<b>Area supervisor Lakshmi</b> — re-check on site', 'Tomorrow', 'k']] },
 'Banquets': { s: 70, d: 'Five outlets normal. <b>Banquets scored 70</b> — one event over budget on wastage (11%), advance for Saturday event unpaid. No complaints.', g: [['Event wastage > 8% · Banquets', '<b>Banquet manager Priya</b> — "Head-count vs cooked quantity for Thursday?"', 'Today 12:00', 'r'], ['Advance unpaid < 3 days to event', '<b>Accounts</b> — reminder ladder started; call if unpaid by tomorrow', 'Tomorrow', 'r'], ['Punctuality 3-day trend · Central bus stand', '<b>HR</b> — roster review; not yet a breach', 'Watch', 'k']] }
};
const GOOD = { 'Cantonment': 92, 'Thillai Nagar': 89, 'Srirangam': 86, 'Woraiyur': 87, 'Central bus stand': 78, 'Banquets': 94 };
outs.forEach(o => { o.setAttribute('role', 'button'); o.tabIndex = 0;
  const pick = () => { const name = o.firstElementChild.textContent.trim(); outs.forEach(x => { x.classList.remove('bad'); const n = x.firstElementChild.textContent.trim(); x.firstElementChild.innerHTML = n; const sc = x.querySelector('.sc'); sc.textContent = GOOD[n]; sc.style.color = GOOD[n] >= 85 ? '#2E7D4F' : '#B26A00'; });
    o.classList.add('bad'); o.firstElementChild.innerHTML = `<b>${name}</b>`; const sc = o.querySelector('.sc'); sc.textContent = D[name].s; sc.style.color = '#D93A2B'; if (status) status.textContent = `${name} selected`;
    const body = dg?.children[1]; if (body) { body.innerHTML = D[name].d; body.classList.remove('reveal'); void body.offsetWidth; body.classList.add('reveal'); }
    D[name].g.forEach((g, i) => { const r = gv[i]; if (!r) return; r.children[0].innerHTML = g[0]; r.children[1].innerHTML = g[1]; r.children[2].innerHTML = `<span class="tag ${g[3]}">${g[2]}</span>`; r.classList.remove('reveal'); void r.offsetWidth; r.classList.add('reveal'); }); };
  o.addEventListener('click', pick); o.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); pick(); } }); });
