# AI calling agent — operator console. Shubham Developers (Surat). Fictional. No product name.
from _lib import *
APP = dict(brand='CallDesk', sub='AI calling agent', client='Shubham Developers', user='Vikram Shah', role='Sales head',
  nav=[('home', 'Today', 'home', None), ('camp', 'Campaigns', 'cal', None), ('live', 'Live calls', 'phone', 4), ('log', 'Call log', 'doc', None), ('script', 'Agent script', 'ladder', None), ('-', 'Control', '', None), ('hand', 'Handovers', 'users', 'g2'), ('reports', 'Reports', 'chart', None)],
  activity=[('14:31', '<b>Priya Mehta</b> · hot · visit Sun 3:00 · Kiran assigned in CRM'), ('14:27', '<b>Suresh Iyer</b> · hot · 3 BHK · budget 1.1 Cr'), ('14:20', '<b>Anil Gupta</b> · price question → Vikram joined at 1:05'), ('14:12', '<b>Overdue EMI</b> campaign · 212 / 340 done · 61% connected'), ('14:00', '<b>Cost</b> · ₹0.81 / min today · 1,284 calls')])
SCREENS = [
 dict(slug='campaigns', nav='camp', title='Campaigns', crumb='Tue 16 Sep · 14:32', topbtn='<button class="btn red">New campaign</button>',
  caption='Every campaign with its progress, outcomes and cost per minute — the agent calls inside 30 seconds of an enquiry or on a schedule you set.',
  body=kpis([('1,284', 'calls placed today', ('62% connected', 'up')), ('91', 'hot leads', ('written to CRM', 'up'), 'r'), ('22', 'handovers', ('9 price', '')), ('₹0.81', 'per call-minute', ('all-in', ''))]) + table(['Campaign', 'Account', 'Trigger', 'Progress', 'Connected', 'Hot', 'Status'], [['<b>Vesu 2BHK · enquiry follow-up</b>', 'Shubham Developers', 'New enquiry → call in 30 s', '640 / 900', '64%', '#71', tag('running', 'g')], ['<b>Overdue EMI · gentle reminder</b>', 'Gupta Pipes dealers', 'Ledger overdue > 7 d · 11:00', '212 / 340', '61%', '#—', tag('running', 'g')], ['<b>Service due · 10,000 km</b>', 'Annapoorna Motors', 'Odometer sync · weekly', '1,180 / 1,180', '58%', '#204 booked', tag('done', '')], ['<b>Renewal · Diwali offer</b>', 'Deccan Protective', 'Scheduled 20 Sep 10:00', '0 / 2,200', '—', '#—', tag('scheduled', 'b')]]) + card('Outcome mix · today', hbars([('Hot', 30, '91', 'r'), ('Callback', 55, '164', ''), ('Handover', 8, '22', 'k'), ('Not interested', 100, '310', ''), ('No answer (retry 2/3)', 100, '486', 'g')]))),
 dict(slug='live', nav='live', title='Live calls', crumb='4 in progress · 3 lines free',
  caption='Calls in progress with stage, sentiment and the transcript as it happens — a supervisor can listen in or take over with one click.',
  body='<div class="grid g4">' + ''.join(f'<div class="card"><div class="row between"><b>{n}</b><span class="mono">{d}</span></div><div class="mono" style="color:var(--red)">{s}</div><div class="spark">' + ''.join(f'<i class="{"on" if j % 3 else ""}" style="height:{h}%"></i>' for j, h in enumerate([30, 60, 45, 80, 55, 70, 40, 90, 65, 50, 75, 35, 60, 85, 45, 70])) + f'</div><div class="row between" style="font-size:11.5px;color:var(--muted)"><span>sentiment</span><span class="pill"><span class="dot {c}"></span>{sv}</span></div><div class="row" style="gap:6px"><button class="btn sm ghost">Listen</button><button class="btn sm ghost">Take over</button></div></div>' for n, d, s, c, sv in [('Priya Mehta', '2:17', 'Booking visit', 'g', '+0.62'), ('Ramesh K', '0:44', 'Qualifying', '', '+0.10'), ('Suresh Iyer', '1:31', 'Objection · price', 'w', '−0.12'), ('Deepa S', '0:09', 'Opening', '', '+0.05')]) + '</div>' + card('Listening in · Priya Mehta', '<div class="list"><div><span class="t" style="width:60px;color:var(--red)">AGENT</span><div>Vesu mein 2 BHK 76 se 84 lakh mein hai, possession March 2027. Aap site visit ke liye kab free hain?</div></div><div><span class="t" style="width:60px">PRIYA</span><div>Sunday afternoon chalega.</div></div><div><span class="t" style="width:60px;color:var(--red)">AGENT</span><div>Perfect — Sunday 3 baje, Kiran aapko site par milenge. Main abhi WhatsApp par location bhej deti hoon.</div></div><div><span class="t" style="width:60px">PRIYA</span><div>Theek hai, thank you.</div></div></div><div class="row" style="gap:8px;margin-top:6px"><span class="tag g">visit · Sun 3:00</span><span class="tag">budget ~80 L</span><span class="tag">2 BHK</span><span class="tag b">→ CRM</span></div>', 'live transcript · 2:17')),
 dict(slug='log', nav='log', title='Call log', crumb='Vesu 2BHK · today · 640 calls', topbtn='<div class="chips"><span class="chip on">All</span><span class="chip">Hot</span><span class="chip">Callback</span><span class="chip">Handover</span><span class="chip">No answer</span></div>',
  caption='Every call becomes a record: transcript, sentiment, entities, next action — and the CRM write that happened because of it.',
  body=table(['Time', 'Caller', 'Number', 'Dur.', 'Outcome', 'Sentiment', 'Note', 'CRM'], [['14:31', '<b>Priya Mehta</b>', '+91 98••• 4471', '2:14', tag('hot', 'r'), '+0.62', 'Visit booked Sun 3:00 · location sent', tag('written', 'g')], ['14:29', '<b>Ramesh K</b>', '+91 99••• 1180', '0:41', tag('callback', 'w'), '+0.10', 'Asked for evening · 7:30', tag('scheduled', 'b')], ['14:27', '<b>Suresh Iyer</b>', '+91 97••• 2290', '3:02', tag('hot', 'r'), '+0.55', 'Wants 3 BHK · budget 1.1 Cr · brochure sent', tag('written', 'g')], ['14:26', 'Unknown', '+91 90••• 0034', '0:00', tag('no answer', ''), '—', 'Retry in 2 h · attempt 2/3', tag('retry', '')], ['14:22', '<b>Kavita Rao</b>', '+91 96••• 8812', '1:12', tag('not interested', ''), '−0.05', 'Already booked elsewhere · no calls 90 d', tag('written', 'g')], ['14:20', '<b>Anil Gupta</b>', '+91 98••• 5567', '1:48', tag('handover', 'k'), '−0.32', 'Price question · Vikram joined at 1:05', tag('written', 'g')], ['14:18', '<b>Deepa S</b>', '+91 95••• 3301', '2:31', tag('hot', 'r'), '+0.71', 'Visit Sat 11:00 · with spouse · school question answered', tag('written', 'g')]], sel=0) + card('Priya Mehta · 14:31 · 2:14', '<div class="grid g3"><div>' + kv([('Sentiment', '+0.62 · engaged'), ('Language', 'Hindi · code-mix'), ('Entities', '2 BHK · ~80 L · Sunday · Kiran')]) + '</div><div>' + kv([('Written to CRM', 'Stage → Hot · visit Sun 3:00'), ('Assigned', 'Kiran (site)'), ('WhatsApp', 'Location + brochure sent 14:32')]) + '</div><div class="row" style="gap:6px;align-items:flex-start"><button class="btn sm ghost">▶ Recording</button><button class="btn sm ghost">Transcript</button></div></div>', 'selected')),
 dict(slug='script', nav='script', title='Agent script · Anjali', crumb='Vesu 2BHK · v7 · edited by Vikram · 12 Sep', topbtn='<button class="btn ghost">Test a line</button>&nbsp;<button class="btn">Publish v8</button>',
  caption='The script is plain language: opening, goal, language mix, objections and the rules for handing over. Your sales head edits it, not an engineer.',
  body='<div class="grid g2">' + '<div class="form">' + card('Voice & goal', form([('Opening', 'Namaste, {name} ji. Main Shubham Developers se Anjali bol rahi hoon. Aapne abhi Vesu project ke liye enquiry ki thi — kya main do minute le sakti hoon?', 'ta'), ('Goal', 'Book a site visit (fallback: qualify budget + timeline)', 'sel'), ('Language mix', 'Hindi 60 / English 40 · mirror the caller', 'sel'), ('Voice', 'Anjali · warm · tuned on our recordings', 'sel')])) + card('Hand over when', switches([('Any price or discount question', True), ('Frustration (sentiment < −0.4)', True), ('Caller asks for a person', True), ('VIP list (top 50)', False)])) + '</div>' + card('Objections · how Anjali answers', '<div class="list">' + ''.join(f'<div><div><b>{q}</b><div style="color:var(--ink2);font-size:12px">{a}</div></div></div>' for q, a in [('"Bahut mehenga hai"', 'Acknowledge; mention 76 L starting; offer the price sheet on WhatsApp; ask what budget works.'), ('"Baad mein call karo"', 'Ask for a specific time, confirm it back, schedule the callback — never a vague "later".'), ('"Kaun bol raha hai?"', 'Repeat name and company, the enquiry source and time; offer a verification message.'), ('"Loan milega?"', 'Yes — partner banks; ask salary band; promise a call from the loan desk within the day.'), ('"Possession kab?"', 'March 2027, RERA number on request; offer to send the RERA page.')]) + '</div>', 'v7') + '</div>'),
 dict(slug='handover', nav='hand', title='Handovers', crumb='2 waiting · when the agent stops and a person starts',
  caption='Handover is designed in: the person gets the transcript, the sentiment, the CRM card and a suggested line — and joins the call or calls back within a promised time.',
  body='<div class="grid" style="grid-template-columns: 1.1fr 1fr">' + card('Waiting', lst([('14:20', '<b>Anil Gupta</b> · 2nd discount request · Vikram joined at 1:05 · outcome pending', tag('on call', 'r')), ('13:52', '<b>Meera Joshi</b> · "I want to speak to a person" · callback promised 15:00 · Rahul', tag('due 15:00', 'w'))]), '2') + card('Anil Gupta · handover brief', kv([('Trigger', 'Price / discount · 2nd time'), ('Sentiment', '−0.32 · impatient'), ('Card', '3 BHK · budget 95 L · visited 12 Sep'), ('Last line', '"Best price batao, warna Pal Gardens dekh lunga"'), ('Suggested', 'Slab: 2% on booking this month (policy) · loan tie-up'), ('Owner', 'Vikram · joined 1:05')]) + '<div class="row" style="margin-top:6px"><button class="btn sm">Join call</button><button class="btn sm ghost">Call back</button></div>', '14:20') + '</div>' + card('Handover rules · this month', hbars([('Price / discount', 62, '138', 'r'), ('Asked for a person', 22, '48', ''), ('Frustration', 9, '20', 'w'), ('VIP', 6, '14', ''), ('Unknown question', 4, '9', '')]) + '<div class="mono">Median time to a human: 38 s on call · 11 min callback</div>')),
 dict(slug='reports', nav='reports', title='Reports', crumb='Sep 2026 · all campaigns', fill=True, topbtn='<div class="chips"><span class="chip">Week</span><span class="chip on">Month</span></div>',
  caption='Connect rates, outcomes, cost per minute and per hot lead — measured, not estimated, and compared against the human desk it replaced.',
  body=kpis([('28,400', 'calls', ('61% connected', '')), ('2,140', 'hot leads', ('₹94 per hot lead', 'up'), 'r'), ('₹0.81', 'per minute', ('₹3.79 on the old stack', 'up')), ('31 s', 'median time to first call', ('was 4 h', 'up'))]) + '<div class="grid g2">' + card('Calls by hour', bars([(15, 'g'), (40, ''), (70, ''), (95, ''), (85, ''), (60, ''), (55, ''), (75, ''), (100, ''), (90, ''), (65, ''), (30, 'g')]) + '<div class="row between mono"><span>09:00</span><span>14:00</span><span>20:00</span></div>') + card('Agent vs human desk · same month last year', table(['', 'Human desk', 'AI agent'], [['Time to first call', '4 h (median)', '31 s'], ['Enquiries called', '68%', '99%'], ['Connected', '54%', '61%'], ['Hot leads / 100 enquiries', '5.1', '7.5'], ['Cost per hot lead', '₹610', '₹94'], ['Calls after 7 pm', '0', '38%']])) + '</div>'),
 dict(slug='crm-write', nav='log', title='What the call wrote', crumb='Priya Mehta · 14:31 → CRM, WhatsApp, calendar', fill=True,
  caption='A call is only useful if it changes a record. Every outcome writes to your CRM, sends the WhatsApp follow-up and books the calendar — automatically.',
  body='<div class="grid g3">' + card('CRM · lead card', kv([('Stage', 'New → <b>Hot</b>'), ('Need', '2 BHK · Vesu'), ('Budget', '~₹80 L'), ('Visit', 'Sun 21 Sep · 15:00'), ('Owner', 'Kiran (site)'), ('Source', 'Website enquiry 14:28')]), 'written 14:33') + card('WhatsApp · sent', wa('Priya Mehta', '+91 98••• 4471', [('me', 'Priya ji, thank you for your time. Site visit confirmed: Sun 21 Sep, 3:00 pm, Vesu Heights. 📍 Location · Kiran: +91 97••• 1180. Brochure attached.', '14:32 · auto')], av='PM'), '14:32') + card('Calendar & tasks', lst([('Sun 15:00', 'Site visit · Kiran · Priya Mehta'), ('Sat 20:00', 'Reminder to Priya (WhatsApp)'), ('Sun 18:00', 'If no-show → AI call to re-book'), ('Mon 10:00', 'Post-visit follow-up · ladder')]), '4 entries') + '</div>'),
]
