# AI workflow automation — Annapoorna Group (Trichy) multi-outlet operations. Fictional.
from _lib import *
APP = dict(brand='RunBook', sub='Workflow automation', client='Annapoorna Group', user='Ramesh V', role='Operations head',
  nav=[('home', 'Today', 'home', None), ('flows', 'Workflows', 'ladder', None), ('runs', 'Runs', 'check', 'g31'), ('exc', 'Exceptions', 'bell', 4), ('appr', 'Approvals', 'users', 2), ('-', 'Setup', '', None), ('conn', 'Connections', 'cog', None), ('reports', 'Reports', 'chart', None)],
  activity=[('12:04', '<b>Wastage > 5%</b> · Thillai Nagar · question sent to Senthil · due 12:00 → escalated'), ('11:40', '<b>Vendor invoice</b> · Sri Murugan Dairy · matched · posted'), ('11:15', '<b>Daily checklist</b> · 6 of 7 outlets submitted · Srirangam missing → reminder'), ('10:30', '<b>Purchase request</b> · Cantonment · rice 200 kg · approved by Ramesh'), ('06:00', '<b>Owner digest</b> · 7 outlets · 2 flags')])
SCREENS = [
 dict(slug='today', nav='home', title='Today · 7 outlets', crumb='Tue 16 Sep · 12:10',
  caption='The operations head\'s view: which workflows ran, which stalled waiting on a person, and the exceptions that need a decision — across every outlet.',
  body=kpis([('31', 'workflow runs today', ('27 completed', 'up')), ('4', 'stalled on a person', ('avg wait 42 min', 'dn'), 'r'), ('2', 'approvals waiting', None), ('₹1.9 L', 'spend routed through approvals', ('0 outside policy', 'up'))]) + '<div class="grid g2">' + card('Stalled · waiting on', lst([('12:00', '<b>Wastage question · Thillai Nagar</b> · Senthil hasn\'t answered · escalated to you', tag('overdue', 'r')), ('11:15', '<b>Daily checklist · Srirangam</b> · not submitted · 2nd reminder sent', tag('reminded', 'w')), ('10:50', '<b>Complaint callback · Cantonment</b> · Devi to call guest · promise 13:00', tag('due 13:00', '')), ('09:30', '<b>Staff late ×3 · Central</b> · HR roster review', tag('watch', ''))]), '4') + card('Ran without anyone', lst([('11:40', 'Vendor invoice matched and posted · Sri Murugan Dairy'), ('11:00', '6 checklists compiled · scores computed · 5 normal'), ('10:30', 'Purchase request → policy check → Ramesh approved on WhatsApp'), ('09:00', 'Stock count variance · Banquets · within tolerance · logged'), ('06:00', 'Owner digest · 7 outlets · 2 flags')]), '27') + '</div>'),
 dict(slug='flow', nav='flows', title='Workflow · Wastage above limit', crumb='Workflows › Governance › Wastage', topbtn='<button class="btn ghost">Simulate</button>&nbsp;<button class="btn">Publish</button>',
  caption='A workflow is a chain of detect → ask → wait → escalate, drawn in plain language. The AI does the reading and chasing; people do the deciding.',
  body='<div class="grid" style="grid-template-columns: 1.4fr 1fr">' + card('Steps', timeline([('Detect: outlet wastage > 5% in the daily compile', 'from checklist + POS · 06:00', 'on'), ('Ask the outlet manager on WhatsApp: "What was wasted and why?" · photo of the log required', 'Senthil · due 12:00', 'on'), ('Read the reply: reason, quantity, one-off or repeat', 'AI · classifies', 'on'), ('If repeat (2nd time in 14 d) → question to area manager', 'Ramesh', 'on'), ('If no reply by due → escalate to operations head with the history', 'Ramesh · 12:04 today', 'r'), ('Log outcome against the outlet · include in owner digest', 'always', 'cur')])) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Trigger & rules', kv([('Runs', 'Daily after compile · 06:10'), ('Threshold', '5.0% · per outlet · can vary by outlet'), ('Owner', 'Outlet manager → Area → Ops head'), ('Waits', '6 h · then escalate'), ('Approvals', 'None — questions only')])) + card('Last 30 days', hbars([('Triggered', 100, '38', ''), ('Answered by rung 2', 66, '25', 'g'), ('Escalated', 26, '10', 'r'), ('Repeat offenders', 8, '3', 'w')])) + '</div></div>'),
 dict(slug='runs', nav='runs', title='Runs', crumb='Today · 31 · every step logged', topbtn='<div class="chips"><span class="chip on">All</span><span class="chip">Stalled</span><span class="chip">Escalated</span></div>',
  caption='Every run, step by step: what was detected, who was asked, what they replied, how long it took — the audit trail of the whole operation.',
  body=table(['Started', 'Workflow', 'Outlet', 'Now at', 'Waiting on', 'Elapsed', 'Status'], [['06:10', '<b>Wastage above limit</b>', 'Thillai Nagar', 'Escalated to ops head', 'Ramesh', '6 h 04 m', tag('escalated', 'r')], ['06:10', '<b>Wastage above limit</b>', 'Cantonment', 'Answered · one-off (event)', '—', '48 m', tag('done', 'g')], ['08:00', '<b>Daily checklist</b>', 'Srirangam', '2nd reminder', 'Outlet manager', '4 h', tag('stalled', 'w')], ['10:14', '<b>Purchase request</b>', 'Cantonment', 'Approved · PO sent', '—', '16 m', tag('done', 'g')], ['10:50', '<b>Guest complaint</b>', 'Cantonment', 'Callback promised 13:00', 'Devi', '1 h 20 m', tag('waiting', '')], ['11:40', '<b>Vendor invoice</b>', 'Central kitchen', 'Posted', '—', '2 m', tag('done', 'g')], ['09:30', '<b>Punctuality trend</b>', 'Central', 'HR roster review', 'HR', '2 h 40 m', tag('watch', '')]], sel=0) + card('Run · Wastage · Thillai Nagar', lst([('06:10', 'Detected: 6.1% wastage (limit 5%) · ₹4,300'), ('06:11', 'Asked Senthil on WhatsApp · photo of log required · due 12:00'), ('09:00', 'Reminder · no reply'), ('12:00', 'Due passed · no reply'), ('12:04', 'Escalated to Ramesh with history: 2nd time in 14 days')]), 'step log')),
 dict(slug='exceptions', nav='exc', title='Exceptions', crumb='4 open', fill=True,
  caption='Exceptions are the point: the workflow surfaces the few things that genuinely need a person, with the history and a suggested action attached.',
  body='<div style="display:flex;flex-direction:column;gap:12px">' + ''.join(f'<div class="card r" style="flex-direction:row;align-items:center;gap:18px"><div style="flex:1"><b>{t}</b><div style="color:var(--ink2);margin-top:2px">{d}</div><div class="mono" style="margin-top:6px">Suggested: {ai}</div></div><span class="mono">{w}</span><button class="btn sm">Act</button><button class="btn sm ghost">Snooze</button></div>' for t, d, ai, w in [('Wastage · Thillai Nagar · 2nd time in 14 days', '6.1% today, 5.8% on 04 Sep · Senthil did not answer the question by 12:00', 'call Senthil; if reason is prep over-ordering, cap Friday prep at 90% of forecast', 'Ops head'), ('Checklist not submitted · Srirangam', 'Two reminders sent; manager online on WhatsApp at 11:50', 'call; mark outlet "unreported" in the owner digest', 'Area mgr'), ('Guest complaint · billing · Cantonment', 'Void log shows 2 voids on shift 2 · ₹4,100 variance', 'have Devi call the guest by 13:00; cashier lead to explain voids', 'Outlet mgr'), ('Punctuality · Central · 3 late in 3 days', 'Not a breach yet · trend', 'HR roster review this week', 'HR')]) + '</div>'),
 dict(slug='approvals', nav='appr', title='Approvals', crumb='2 waiting · anything that spends money stops here', fill=True,
  caption='Purchase requests, refunds and vendor payments pass a policy check first, then a named person — on WhatsApp if they are not at a desk.',
  body='<div class="grid g2">' + card('Waiting', lst([('11:58', '<b>Purchase · Srirangam</b> · oil 60 L · ₹9,600 · policy ok · vendor on list', '<button class="btn sm">Approve</button>'), ('11:20', '<b>Refund · Banquets</b> · ₹12,000 · event cancelled · policy: refund 80%', '<button class="btn sm">Approve ₹9,600</button>')]), '2') + card('Approved on WhatsApp · 10:30', wa('RunBook', 'Approvals', [('', 'Purchase request · Cantonment · Rice 200 kg · ₹11,800 · Sri Murugan Traders (listed) · within weekly budget (₹38k of ₹60k). Reply 1 to approve, 2 to query.', '10:14'), ('me', '1', '10:29'), ('', 'Approved. PO sent to Sri Murugan. GRN expected Wed.', '10:30')], av='RB'), 'no desk needed') + '</div>' + card('Policy checks · this month', hbars([('Requests', 100, '212', ''), ('Passed policy · auto-routed', 91, '193', 'g'), ('Outside policy · flagged', 9, '19', 'r'), ('Approved within 1 h', 78, '166', '')]))),
 dict(slug='connections', nav='conn', title='Connections', crumb='What the workflows read and write', fill=True,
  caption='Workflows read from the systems you already have — POS, Tally, sheets, WhatsApp, phone checklists — and write back to them. Nothing has to be replaced first.',
  body=table(['System', 'Direction', 'Used by', 'Last sync', 'Health'], [['<b>POS · 7 outlets</b>', 'Read', 'Sales, voids, discounts, covers', '11:58', tag('ok', 'g')], ['<b>Phone checklists</b>', 'Read', 'Hygiene, wastage, punctuality', '11:15 · 6 of 7', tag('1 missing', 'w')], ['<b>Tally</b>', 'Read + write', 'Vendor invoices, payments', '11:40', tag('ok', 'g')], ['<b>WhatsApp Business</b>', 'Read + write', 'Questions, approvals, digests', 'live', tag('ok', 'g')], ['<b>Purchase sheet · Google</b>', 'Read + write', 'Requests, PO log', '10:30', tag('ok', 'g')], ['<b>Biometric attendance</b>', 'Read', 'Punctuality', '09:00', tag('ok', 'g')]])),
 dict(slug='digest', nav='home', title='Owner digest', crumb='06:00 · Tue 16 Sep · 7 outlets', fill=True,
  caption='The owner reads one message a day. Every line in it came from a workflow — a number, a question, a person and a deadline.',
  body='<div class="grid g2">' + digest('☀ Annapoorna · Tue 16 Sep', ['<b>Six outlets normal.</b> Thillai Nagar scored 68 — wastage 6.1% (limit 5%), 2nd time in 14 days. Senthil asked by 12:00.', '<b>Cantonment</b> — billing variance ₹4,100 on shift 2; guest complaint (billing). Devi calls the guest by 13:00; Prakash explains the voids.', '<b>Srirangam</b> — checklist not submitted by 11:00; 2 reminders sent.', '<b>Spend</b> — ₹1.9 L routed through approvals yesterday; 0 outside policy.', '<b>Yesterday\'s sales</b> — ₹6.4 L · +4% vs last Tue · Banquets ₹1.1 L.', '<span class="mono">Reply "1" for Thillai Nagar history · "2" for Cantonment voids</span>']) + card('How each line was made', lst([('68', 'Score from checklist + POS · weights set by owner'), ('6.1%', 'Wastage log ÷ consumption · flagged by workflow'), ('12:00', 'Question sent 06:11 · deadline rule 6 h'), ('₹4,100', 'POS voids on shift 2 vs cash'), ('13:00', 'Complaint workflow · callback rung')]), 'no typing') + '</div>'),
]
