# Dealer & distributor order management — Gupta Pipes (Lucknow). Fictional.
from _lib import *
APP = dict(brand='DealerHub', sub='Dealer order management', client='Gupta Pipes', user='Vikram Gupta', role='Sales manager',
  nav=[('home', 'Today', 'home', None), ('orders', 'Dealer orders', 'box', 12), ('dealers', 'Dealers & credit', 'users', None), ('coll', 'Collections', 'rupee', 'g9'), ('schemes', 'Schemes', 'cal', None), ('-', 'Field', '', None), ('field', 'Field app', 'phone', None), ('reports', 'Reports', 'chart', None)],
  activity=[('11:32', '<b>DO-26-1187</b> · Sharma Traders · ₹1.86 L · credit ok · allocated Agra + Kanpur · WhatsApp sent'), ('11:05', '<b>Agarwal Sanitary</b> · ₹42,000 overdue 9 d · reminder ladder rung 2'), ('10:40', '<b>New dealer</b> · Aminabad hardware · onboarding checklist 3/5'), ('09:30', '<b>Scheme</b> · Diwali SWR 3% · 41 dealers qualified so far'), ('06:00', '<b>Digest</b> · ₹18.4 L collected yesterday · 3 dealers over limit')])
SCREENS = [
 dict(slug='today', nav='home', title='Today', crumb='Tue 16 Sep · 312 dealers · 3 depots',
  caption='Dealer orders from WhatsApp and the app, credit checked before they are accepted, allocated across depots — and the money side visible on the same screen.',
  body=kpis([('₹24.6 L', 'orders today · 48', ('+12% vs avg Tue', 'up')), ('12', 'orders waiting credit / stock', ('4 over limit', ''), 'r'), ('₹1.8 Cr', 'receivables', ('₹31 L overdue', 'dn')), ('96%', 'dispatched same day', ('target 95%', 'up'))]) + '<div class="grid g2">' + card('Needs you', lst([('11:40', '<b>Verma Hardware</b> · order ₹2.4 L · would exceed credit by ₹60k · 2 invoices overdue', '<button class="btn sm">Decide</button>'), ('11:05', '<b>Agarwal Sanitary</b> · ₹42,000 overdue 9 d · promised Fri on the AI call', tag('watch', 'w')), ('10:12', '<b>110mm SWR</b> · Kanpur depot 3 days of stock · transfer from Lucknow drafted', '<button class="btn sm ghost">Approve</button>'), ('09:30', '<b>Diwali scheme</b> · 41 dealers qualified · 12 within ₹20k of slab', tag('nudge', 'b'))]), '4') + card('Orders by channel · today', hbars([('WhatsApp (bot)', 100, '29', ''), ('Dealer app', 52, '15', ''), ('Field rep', 14, '4', 'g')]) + '<div class="mono">0 orders typed by the office</div>') + '</div>'),
 dict(slug='order', nav='orders', title='Order · DO-26-1187', crumb='Dealer orders › Sharma Traders · Kanpur', topbtn='<button class="btn ghost">Message dealer</button>&nbsp;<button class="btn">Confirm dispatch</button>',
  caption='An order placed on WhatsApp at 9 pm: parsed, priced from the dealer\'s slab, credit-checked, allocated across two depots and confirmed back — before the office opened.',
  body='<div class="grid" style="grid-template-columns: 1fr 1.2fr">' + wa('Sharma Traders · Ramesh', 'Dealer · Kanpur', [('', '40 pipe 110mm 3m, 120 elbow 110, 60 tee 110 bhej do', '21:02'), ('me', 'Order DO-26-1187 received:<br>• SWR 110mm × 3m — 40 @ ₹1,260<br>• Elbow 110 — 120 @ ₹86<br>• Tee 110 — 60 @ ₹118<br><b>Total ₹1,86,400</b> (slab B, +GST). Credit OK (₹4.2 L of ₹6 L). Dispatch tomorrow, ETA Thu. Reply OK to confirm.', '21:02 · bot'), ('', 'ok', '21:04'), ('sys', 'Confirmed · allocated: Agra depot (pipes) + Kanpur depot (fittings) · gate pass 09:10')], av='ST') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Checks', table(['Check', 'Result'], [['Dealer & slab', 'Sharma Traders · slab B · 2% scheme applicable'], ['Credit', '₹4.2 L used of ₹6 L · 0 overdue → <b>OK</b>'], ['Stock', 'Pipes: Agra 380 · Kanpur 12 → split allocation'], ['Price', 'From price list 12 Sep · no manual entry'], ['Scheme', 'Diwali SWR 3% → ₹1,512 credit note at month end']]), 'all automatic') + card('Fulfilment', timeline([('Allocated Agra + Kanpur', '21:02', 'on'), ('Gate pass · LR 44821 · Verma Roadways', '09:10', 'on'), ('Dispatched 14:10 · dealer told on WhatsApp', '14:10', 'on'), ('ETA Kanpur Thu 18 Sep', 'tracking', 'cur'), ('Invoice GP/2291 · due 18 Oct', 'posted to Tally', '')])) + '</div></div>'),
 dict(slug='dealers', nav='dealers', title='Dealers & credit', crumb='312 dealers · one credit position each', topbtn='<div class="chips"><span class="chip on">Over limit</span><span class="chip">Top 50</span><span class="chip">New</span></div>',
  caption='One credit position per dealer — limit, used, overdue, promise dates from the AI calls — and the rule for what happens when an order would cross the line.',
  body=table(['Dealer', 'City', 'Slab', 'Limit', 'Used', 'Overdue', 'Last promise', 'Rule'], [['<b>Verma Hardware</b>', 'Agra', 'B', '#₹4.0 L', '#₹3.8 L', '#₹1.1 L · 14 d', 'Wed (AI call 15 Sep)', tag('hold new orders', 'r')], ['<b>Agarwal Sanitary</b>', 'Lucknow', 'A', '#₹8.0 L', '#₹6.9 L', '#₹42,000 · 9 d', 'Fri (AI call today)', tag('warn on order', 'w')], ['<b>Sharma Traders</b>', 'Kanpur', 'B', '#₹6.0 L', '#₹4.2 L', '#0', '—', tag('ok', 'g')], ['<b>Singh Pipes</b>', 'Bareilly', 'C', '#₹2.0 L', '#₹2.1 L', '#₹18,000 · 4 d', 'Mon', tag('over limit · owner', 'r')], ['<b>Aminabad Hardware</b>', 'Lucknow', 'new', '#₹1.0 L', '#₹0', '#0', '—', tag('onboarding 3/5', 'b')]], sel=0) + card('Verma Hardware · what the rule does', kv([('Order ₹2.4 L', 'Would take used to ₹6.2 L vs limit ₹4.0 L'), ('Overdue', '2 invoices · ₹1.1 L · 14 days'), ('Rule', 'Hold; dealer told politely; AI call for a payment date; Vikram decides'), ('AI call', 'Promised Wed · ₹60k'), ('Suggested', 'Release ₹1.2 L now (fast movers), rest on payment')]) + '<div class="row" style="margin-top:6px"><button class="btn sm">Release partial</button><button class="btn sm ghost">Hold</button></div>', '11:40')),
 dict(slug='collections', nav='coll', title='Collections', crumb='₹31 L overdue · ladders running on 38 dealers', fill=True,
  caption='Collections chase themselves: reminder, WhatsApp, AI call for a date, field-rep visit, owner — and every promise is held against the dealer.',
  body='<div class="grid" style="grid-template-columns: 1.3fr 1fr">' + table(['Dealer', 'Overdue', 'Days', 'Rung', 'Last', 'Promise', 'Next'], [['<b>Verma Hardware</b>', '#₹1.1 L', '14', '4 · field visit', 'AI call 15 Sep', 'Wed ₹60k', 'Rep visit Thu'], ['<b>Agarwal Sanitary</b>', '#₹42,000', '9', '3 · AI call', 'Today 11:05', 'Fri', 'Check Fri 18:00'], ['<b>Singh Pipes</b>', '#₹18,000', '4', '2 · WhatsApp', 'Yesterday', 'Mon', 'Reminder Mon 10:00'], ['<b>Mishra Traders</b>', '#₹2.2 L', '31', '5 · owner', 'Owner call 12 Sep', 'partial ₹1 L Sat', 'Hold orders'], ['<b>Jain Hardware</b>', '#₹9,400', '2', '1 · reminder', 'Today 06:00', '—', 'WhatsApp +2 d']]) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Ladder · overdue invoice', '<div class="ladder"><div class="rung"><span class="w">Due +1 d</span><span class="dt"></span><div>Reminder with invoice copy</div></div><div class="rung"><span class="w">+3 d</span><span class="dt"></span><div>WhatsApp — asks for a date</div></div><div class="rung"><span class="w">+7 d</span><span class="dt k"></span><div>AI call · captures promise</div></div><div class="rung"><span class="w">+14 d</span><span class="dt r"></span><div>Field rep visit · new orders held</div></div><div class="rung"><span class="w">+30 d</span><span class="dt r"></span><div>Owner call · in digest</div></div></div>') + card('30 days', hbars([('Collected', 100, '₹1.62 Cr', 'g'), ('Promised → kept', 71, '71%', ''), ('Overdue > 30 d', 12, '₹3.8 L', 'r')])) + '</div></div>'),
 dict(slug='schemes', nav='schemes', title='Schemes', crumb='Diwali SWR 3% · 01 Sep – 31 Oct', fill=True, topbtn='<button class="btn">New scheme</button>',
  caption='Schemes computed on live orders — who has qualified, who is close, and the nudge that goes out to dealers within reach of the next slab.',
  body=kpis([('41', 'dealers qualified', ('of 312', '')), ('₹2.1 L', 'credit notes accrued', None), ('12', 'within ₹20k of slab', ('nudged today', 'up'), 'r'), ('+18%', 'SWR volume vs Aug', ('scheme effect', 'up'))]) + '<div class="grid g2">' + card('Slabs', table(['Slab', 'SWR purchases · Sep–Oct', 'Benefit', 'Dealers'], [['1', '≥ ₹2 L', '2% credit note', '#41'], ['2', '≥ ₹5 L', '3% + free freight', '#9'], ['3', '≥ ₹10 L', '4% + Diwali gift', '#2']])) + card('Nudge · sent today', wa('Singh Pipes · Harpreet', 'Dealer · Bareilly', [('me', 'Harpreet ji, Diwali scheme: aap ₹1.82 L par hain — sirf ₹18,000 aur SWR order karke 2% credit note (₹4,000+) mil jayega. Stock Bareilly depot mein hai. Order karein?', '10:02 · auto'), ('', '20 pipe 110 bhej do', '10:40'), ('sys', 'Order DO-1190 · ₹25,200 · slab 1 reached · credit note ₹4,144 at month end')], av='SP')) + '</div>'),
 dict(slug='field', nav='field', title='Field app', crumb='Rep · Anil · Agra beat · Thu', 
  caption='Field reps see their beat, each dealer\'s credit and last order, and take orders or payments on the phone — synced when the signal returns.',
  body='<div class="row top" style="gap:32px">' + phone('Thu · Agra beat', '6 visits · 2 collections', '<div class="card" style="padding:12px 14px;gap:6px;border-color:var(--red)"><div class="row between"><b>Verma Hardware</b><span class="tag r">collect ₹60k</span></div><div style="font-size:12px;color:var(--ink2)">Overdue ₹1.1 L · promised Wed · orders on hold</div><div style="font-size:12px">Last order: 02 Sep · ₹1.9 L · slab B</div><div class="row" style="gap:6px;margin-top:4px"><button class="btn sm">Record payment</button><button class="btn sm ghost">Call</button></div></div><div class="card" style="padding:12px 14px;gap:4px"><div class="row between"><b>Jain Hardware</b><span class="tag">order</span></div><div style="font-size:12px;color:var(--ink2)">Credit ok · scheme: ₹30k to slab 1</div></div><div class="card" style="padding:12px 14px;gap:4px"><div class="row between"><b>Agra Pipes</b><span class="tag b">new</span></div><div style="font-size:12px;color:var(--ink2)">Onboarding · GST + shop photo pending</div></div><div class="card flat" style="padding:10px 12px;font-size:11.5px;color:var(--muted)">Offline: 2 payments queued · will sync</div>') + card('Payment recorded · Verma Hardware · 11:52', kv([('Amount', '₹60,000 · UPI · ref 4471…'), ('Against', 'GP/2214 (₹42,000) + part GP/2230'), ('Credit now', '₹3.2 L used of ₹4.0 L'), ('Effect', 'Held order DO-1191 released · ₹1.2 L · dispatch today'), ('Receipt', 'Sent to dealer on WhatsApp'), ('Tally', 'Receipt voucher posted')]), 'one tap', 'style="max-width:560px"') + '</div>'),
 dict(slug='reports', nav='reports', title='Reports', crumb='Sep 2026 · 3 depots', fill=True, topbtn='<div class="chips"><span class="chip">Week</span><span class="chip on">Month</span></div>',
  caption='Orders, fill rate, receivables ageing and scheme cost — by depot, by rep, by dealer — compiled every night.',
  body=kpis([('₹5.9 Cr', 'dealer orders', ('+14% MoM', 'up')), ('96%', 'same-day dispatch', None), ('38 d', 'DSO', ('was 52', 'up'), 'r'), ('₹2.1 L', 'scheme cost', ('+18% SWR volume', ''))]) + '<div class="grid g2">' + card('Receivables ageing', bars([(100, 'g'), (60, ''), (30, ''), (18, 'r'), (12, 'r')]) + '<div class="row between mono"><span>current</span><span>1–15</span><span>16–30</span><span>31–60</span><span>60+</span></div>') + card('By rep', table(['Rep', 'Beat', 'Orders', 'Collected', 'New dealers'], [['Anil', 'Agra', '#₹1.4 Cr', '#₹38 L', '#3'], ['Mohan', 'Kanpur', '#₹1.9 Cr', '#₹52 L', '#2'], ['Suresh', 'Bareilly', '#₹0.8 Cr', '#₹21 L', '#4'], ['Bot + app', 'All', '#₹1.8 Cr', '#—', '#6']])) + '</div>'),
]
