# Invoice & PO processing — Arasu Knits (Tiruppur). Fictional.
from _lib import *
APP = dict(brand='DocFlow', sub='Document AI', client='Arasu Knits', user='Uma S', role='Accounts',
  nav=[('home', 'Queue', 'inbox', 6), ('doc', 'Documents', 'doc', None), ('match', 'Matching', 'check', None), ('exc', 'Exceptions', 'bell', 2), ('post', 'Posting', 'rupee', None), ('-', 'Setup', '', None), ('src', 'Sources', 'truck', None), ('reports', 'Reports', 'chart', None)],
  activity=[('11:42', '<b>DP/26-27/1183</b> · rate mismatch ₹186 vs ₹181.50 · held · query drafted'), ('11:30', '<b>Nordic PO NR-4488</b> · read from portal · order 631KX created · 12,000 pcs'), ('11:12', '<b>WeTransfer link</b> · 30 tech packs · fanned out to 30 styles · 9 new'), ('10:50', '<b>4 supplier invoices</b> matched to PO + GRN · posted to Tally'), ('06:00', '<b>Overnight</b> · 51 documents read · 47 clean · 4 exceptions')])
SCREENS = [
 dict(slug='queue', nav='home', title='Queue', crumb='51 documents since yesterday · 47 clean · 4 need a decision', topbtn='<button class="btn ghost">Upload</button>',
  caption='Every document that arrived — by email, WhatsApp, portal or link — read, matched and sorted into clean or needs-a-decision. Nobody re-types anything.',
  body=kpis([('51', 'documents · 24 h', ('5 channels', '')), ('47', 'read & matched clean', ('posted automatically', 'up')), ('4', 'exceptions', ('2 rate · 1 qty · 1 unknown', ''), 'r'), ('1.8 s', 'per document', ('0 re-typed', 'up'))]) + table(['Received', 'Channel', 'Document', 'From', 'Read as', 'Match', 'Status'], [['11:42', tag('WhatsApp', 'g'), '<b>Invoice DP/26-27/1183</b>', 'Deccan Polymers', 'Supplier invoice · ₹4,38,960', 'PO-4471 · GRN 1183', tag('rate mismatch', 'r')], ['11:30', tag('Portal', 'b'), '<b>PO NR-4488</b>', 'Nordic Retail', 'Buyer PO · 12,000 · 631KX', 'new order', tag('order created', 'g')], ['11:12', tag('Link', ''), '<b>30 × tech pack PDF</b>', 'Koso Tex · WeTransfer', 'Tech packs · batch', '30 styles · 9 new', tag('fanned out', 'g')], ['10:50', tag('Email', ''), '<b>Invoice SF/2291</b>', 'Shree Fabrics', 'Supplier invoice · ₹1,12,400', 'PO-4462 · GRN 1179', tag('posted', 'g')], ['10:48', tag('Email', ''), '<b>PO amendment</b>', 'Koso Tex portal', 'Qty 6,400 → 6,000 · 588MC', 'PO 4468', tag('order updated', 'g')], ['09:15', tag('WhatsApp', 'g'), '<b>Delivery note</b>', 'Verma Roadways', 'LR 44821 · 40 cartons', 'PO 4459', tag('qty short 2', 'w')], ['08:40', tag('Email', ''), '<b>Unknown attachment</b>', 'unknown@gmail.com', 'Price list? 3 pages', '—', tag('needs a look', 'w')]], sel=0)),
 dict(slug='document', nav='doc', title='Invoice DP/26-27/1183', crumb='Deccan Polymers · WhatsApp · 11:42', topbtn='<button class="btn ghost">Send query</button>&nbsp;<button class="btn">Approve at PO rate</button>',
  caption='The document beside what was read from it, field by field with confidence — and the match against the PO, the GRN and the arithmetic.',
  body='<div class="grid" style="grid-template-columns: 1fr 1.2fr">' + '<div class="doc"><div class="dl"><b style="color:var(--ink)">DECCAN POLYMERS PVT LTD</b><span>TAX INVOICE</span></div><div class="dl"><span>Invoice no. <span class="mark g">DP/26-27/1183</span></span><span>Date <span class="mark g">12-09-2026</span></span></div><div class="dl"><span>GSTIN 27AABCD1234E1Z5</span><span>PO ref <span class="mark g">PO-4471</span></span></div><div style="border-top:1px solid var(--line);margin:4px 0"></div><div class="dl"><span>Bill to: Arasu Knits, Tiruppur</span><span>Ship to: Unit 2</span></div><div class="dl"><span><span class="mark">ABS granules, black, 25 kg bags</span></span><span><span class="mark">2,000 kg</span> × <span class="mark">₹186.00</span></span></div><div class="dl"><span>HSN 39033000</span><span>₹3,72,000.00</span></div><div class="dl"><span>CGST 9% + SGST 9%</span><span>₹66,960.00</span></div><div class="dl"><b style="color:var(--ink)">Total</b><span class="mark g"><b>₹4,38,960.00</b></span></div><div class="dl" style="color:var(--muted)"><span>Payment terms: 45 days</span><span>Bank: HDFC ····8821</span></div></div>' + card('Extracted → matched', table(['Field', 'Read', 'Conf.', 'Check'], [['Supplier', 'Deccan Polymers · GSTIN verified', '#99%', tag('ok', 'g')], ['Invoice', 'DP/26-27/1183 · 12 Sep', '#99%', tag('ok', 'g')], ['PO', 'PO-4471 · open · 2,000 kg ordered', '#98%', tag('match', 'g')], ['Item', 'ABS granules black · RM-0142', '#96%', tag('ok', 'g')], ['Quantity', '2,000 kg billed · <b>GRN 1183: 1,960 kg</b>', '#97%', tag('40 kg short', 'w')], ['Rate', '₹186.00 · <b>PO says ₹181.50</b> (+2.5%)', '#99%', tag('mismatch', 'r')], ['Tax', '18% · ₹66,960 · arithmetic ok', '#—', tag('ok', 'g')], ['Due', '27 Oct 2026 · 45 days', '#—', tag('ok', 'g')]]), '1 exception') + '</div>' + '<div class="card r"><b>Held for approval — rate is 2.5% above PO and 40 kg short-received.</b><div>Suggested: accept at PO rate for 1,960 kg (₹3,55,740 + GST) and ask Deccan for a revised invoice. Draft reply ready. Posts to Tally on approval.</div></div>'),
 dict(slug='matching', nav='match', title='Matching rules', crumb='3-way match · what posts alone and what stops', topbtn='<button class="btn">Save</button>',
  caption='Your matching rules in plain terms: tolerances, who approves what, which documents post on their own — the AI applies them, a person owns the exceptions.',
  body='<div class="grid g2">' + card('Rules', table(['Check', 'Tolerance', 'If outside', 'Approver'], [['Rate vs PO', '±1.0%', 'Hold · draft query to supplier', 'Accounts'], ['Quantity vs GRN', '±0.5%', 'Hold · pay for received qty', 'Accounts'], ['Arithmetic & GST', 'exact', 'Hold · draft query', 'Accounts'], ['Duplicate invoice no.', '—', 'Reject · notify supplier', 'auto'], ['Vendor GSTIN', 'must verify', 'Hold', 'Accounts'], ['Amount > ₹5 L', '—', 'Second approver', 'Raj']])) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Posts without a person', switches([('Invoices matched within tolerance', True), ('Buyer PO amendments (qty, date) → order update', True), ('Delivery notes matched to dispatch', True), ('Anything with a rate or amount outside tolerance', False)]), 'auto') + card('This month', hbars([('Documents read', 100, '1,184', ''), ('Posted automatically', 87, '1,030', 'g'), ('Held for a decision', 11, '128', 'w'), ('Rejected (duplicate/unknown)', 2, '26', 'r')])) + '</div></div>'),
 dict(slug='exceptions', nav='exc', title='Exceptions', crumb='2 open · each with a suggested resolution', fill=True,
  caption='The exception queue is short and specific: what is wrong, what the system suggests, and one click to resolve — with the query already drafted.',
  body='<div style="display:flex;flex-direction:column;gap:12px">' + ''.join(f'<div class="card r" style="flex-direction:row;align-items:center;gap:18px"><div style="flex:1"><b>{t}</b><div style="color:var(--ink2);margin-top:2px">{d}</div><div class="mono" style="margin-top:6px">Suggested: {ai}</div></div><span class="mono">{w}</span><button class="btn sm">Resolve</button><button class="btn sm ghost">Query</button></div>' for t, d, ai, w in [('Invoice DP/26-27/1183 · Deccan Polymers · rate', 'Billed ₹186.00/kg, PO ₹181.50 · 1,960 kg received vs 2,000 billed', 'approve ₹3,55,740 + GST at PO rate for received qty; send drafted revised-invoice request', 'Accounts'), ('Delivery note LR 44821 · Verma Roadways · qty', '40 cartons on note, 38 scanned at gate · PO 4459', 'log 2-carton shortage against transporter; hold 5% of freight invoice; claim drafted ₹3,200', 'Stores')]) + '</div>'),
 dict(slug='posting', nav='post', title='Posting', crumb='To Tally · today · 47 vouchers', topbtn='<button class="btn ghost">Open in Tally</button>',
  caption='Clean documents post to your accounting system as vouchers, with the document attached — so the audit trail is the document itself.',
  body=table(['Time', 'Voucher', 'Party', 'Amount', 'Ledger', 'Document', 'Status'], [['11:30', 'Sales order · SO-2291', 'Nordic Retail', '#$48,000', 'Export sales', 'PO NR-4488', tag('posted', 'g')], ['10:50', 'Purchase · PV-1184', 'Shree Fabrics', '#₹1,12,400', 'Fabric purchases', 'SF/2291', tag('posted', 'g')], ['10:22', 'Purchase · PV-1183', 'Kumar Threads', '#₹18,900', 'Trims', 'KT/0091', tag('posted', 'g')], ['09:58', 'Purchase · PV-1182', 'Deccan Polymers', '#₹2,10,600', 'Raw material', 'DP/1180', tag('posted', 'g')], ['09:40', 'Journal · freight', 'Verma Roadways', '#₹14,200', 'Freight inward', 'LR 44790', tag('posted', 'g')], ['—', 'Purchase · PV-1185', 'Deccan Polymers', '#₹4,38,960', 'Raw material', 'DP/1183', tag('held · rate', 'r')]]) + '<div class="grid g3">' + kpi('47', 'vouchers today', ('0 typed', 'up')) + kpi('₹9.4 L', 'posted', None) + kpi('1', 'held', ('₹4.39 L', ''), 'r') + '</div>'),
 dict(slug='sources', nav='src', title='Sources', crumb='Where documents come from · 5 channels · 3 portals', fill=True,
  caption='Email inboxes, WhatsApp numbers, buyer portals and transfer links — watched continuously. A missed document is reported as missed, never silently dropped.',
  body=table(['Source', 'Type', 'Watches', 'Documents · 30 d', 'Last seen', 'Health'], [['<b>orders@arasuknits.in</b>', 'Mailbox', 'POs, amendments, invoices, tech packs', '#412', '11:30', tag('ok', 'g')], ['<b>accounts@arasuknits.in</b>', 'Mailbox', 'Supplier invoices, credit notes', '#286', '11:42', tag('ok', 'g')], ['<b>+91 98••• 0002</b>', 'WhatsApp', 'Invoices, delivery notes, photos', '#214', '11:42', tag('ok', 'g')], ['<b>Nordic Retail portal</b>', 'Portal · login', 'POs, amendments, comments', '#96', '11:30', tag('ok', 'g')], ['<b>Koso Tex portal</b>', 'Portal · login', 'POs, tech packs', '#71', '10:48', tag('ok', 'g')], ['<b>Laxmi Exports portal</b>', 'Portal · login', 'POs', '#22', '2 d ago', tag('login expired', 'r')], ['<b>Transfer links</b>', 'WeTransfer / Drive', 'Tech pack batches', '#83', '11:12', tag('ok', 'g')]]) + '<div class="card r" style="flex-direction:row;align-items:center;gap:14px"><div style="flex:1"><b>Laxmi Exports portal · login expired 2 days ago.</b> No documents fetched since Sun. Re-enter credentials or the next PO will be missed — and reported as missed.</div><button class="btn sm">Fix login</button></div>'),
 dict(slug='batch', nav='doc', title='Batch · 30 tech packs from one link', crumb='Koso Tex · WeTransfer · 11:12', fill=True,
  caption='One link, thirty PDFs. Each file is matched to its style by the code in the filename, filled in where the style exists, and creates an unconfirmed style where it doesn\'t.',
  body='<div class="grid" style="grid-template-columns: 1fr 1.3fr">' + card('Batch', kv([('Link', 'WeTransfer · expires 18 Sep'), ('Files', '30 PDFs · 214 MB'), ('Matched to existing styles', '21'), ('Created as unconfirmed styles', '9'), ('Unmatched', '0'), ('Picker', 'chose "Docs" over "Graphic files"')]) + '<div class="mono" style="margin-top:6px">Downloaded before expiry · sweep would not have caught this</div>', 'fanned out') + table(['File', 'Code', 'Style', 'Action', 'Status'], [['631KX_AW26_techpack_v3.pdf', '631KX', 'Boys hoodie · 280 gsm', 'Pack v3 attached · v2 archived', tag('filled', 'g')], ['588MC_set_rev2.pdf', '588MC', 'Girls set', 'Pack attached', tag('filled', 'g')], ['702KL_AW26.pdf', '702KL', '— new —', 'Style created · unconfirmed', tag('created', 'b')], ['702KM_AW26.pdf', '702KM', '— new —', 'Style created · unconfirmed', tag('created', 'b')], ['512KU_leggings_v4.pdf', '512KU', 'Leggings', 'Pack v4 attached', tag('filled', 'g')], ['…25 more', '', '', '', '']]) + '</div>'),
]
