# Garment & textile ERP — Arasu Knits (Tiruppur). Fictional.
from _lib import *
APP = dict(brand='LoomLine', sub='Garment & textile ERP', client='Arasu Knits', user='Meena R', role='Merchandiser',
  nav=[('home', 'Today', 'home', None), ('styles', 'Styles & pricing', 'doc', 4), ('sampling', 'Sampling', 'check', None), ('orders', 'Orders & T&A', 'cal', None), ('insp', 'Inspections', 'bell', None), ('ship', 'Shipments', 'truck', None), ('-', 'Control', '', None), ('appr', 'Approvals', 'users', 3), ('reports', 'Reports', 'chart', None)],
  activity=[('10:16', '<b>PO 4471</b> · buyer moved delivery to 12 Oct · T&A re-planned · 2 tasks'), ('09:38', '<b>PO 4468</b> · print end 06 Oct from Koso Tex · decision for Meena'), ('09:00', '<b>631KX</b> · buyer comment on sample rev 2 · reply drafted'), ('08:12', '<b>GRN 1183</b> · fabric received 1,960 kg · stage marked'), ('06:00', '<b>Digest</b> · 212 orders · 9 will miss ETD')])
SCREENS = [
 dict(slug='today', nav='home', title='Today', crumb='Tue 16 Sep · 212 live orders · $2.18M',
  caption='Sourcing, sampling, T&A and inspections on one system — the merchandiser\'s morning is a short list, not seven spreadsheets.',
  body=kpis([('$2.18M', 'live order book', ('212 orders · 3 buyers', '')), ('9', 'will miss ETD', ('was 11', 'up'), 'r'), ('14', 'styles awaiting price', ('48-h clock', '')), ('7', 'spreadsheets retired', None)]) + '<div class="grid g2">' + card('Needs you', lst([('PO 4468', '<b>Print 4 days late</b> · Koso Tex gave 06 Oct on the AI call · ETD holds with 1 day slack', '<button class="btn sm">Decide</button>'), ('631KX', '<b>Buyer comment on sample rev 2</b> · "neckline 1 cm wider" · reply drafted', '<button class="btn sm ghost">Review</button>'), ('382KY', '<b>Price due in 6 h</b> · factory quote ₹186 in · benchmark ₹181 on similar styles', '<button class="btn sm ghost">Price</button>'), ('PO 4459', '<b>Final inspection tomorrow 10:00</b> · Uttarasami assigned · packing list missing', '<button class="btn sm ghost">Open</button>')]), '4') + card('Order book by stage', hbars([('Sampling', 14, '30', ''), ('Fabric', 22, '47', ''), ('Cutting', 9, '19', ''), ('Sewing', 31, '66', ''), ('Finishing', 12, '25', ''), ('Inspection', 6, '13', ''), ('Dispatch', 6, '12', 'g')]) + '<div class="mono">By buyer: Nordic 48% · Koso 31% · Laxmi 21%</div>') + '</div>'),
 dict(slug='styles', nav='styles', title='Styles & pricing', crumb='Season AW26 · 14 awaiting price · 48-hour clock', topbtn='<div class="chips"><span class="chip on">Awaiting price</span><span class="chip">Quoted</span><span class="chip">Confirmed</span></div>',
  caption='Every style that hits a mailbox is created with its tech pack; pricing runs on a 48-hour clock from receipt, benchmarked against similar confirmed styles.',
  body=table(['Style', 'Buyer', 'Product', 'Received', 'Clock', 'Factory quote', 'Benchmark', 'Status'], [['<b>382KY</b>', 'Nordic', 'Boys tee · 180 gsm', '15 Sep 09:10', tag('6 h left', 'r'), '₹186 · Koso', '₹181 (3 similar)', tag('price now', 'r')], ['<b>631KX</b>', 'Nordic', 'Boys hoodie · 280 gsm', '14 Sep', tag('quoted', 'g'), '₹412 · ECC', '₹405', tag('sent $5.10', 'g')], ['<b>588MC</b>', 'Koso', 'Girls set', '14 Sep', tag('quoted', 'g'), '₹298 · Laxmi', '₹290', tag('sent $3.70', 'g')], ['<b>702KL</b>', 'Koso', '— from tech-pack batch —', '16 Sep 11:12', tag('46 h left', ''), 'RFQ sent to 2', '—', tag('awaiting quote', 'b')], ['<b>104CM</b>', '?', 'read from size column', '13 Sep', tag('held', ''), '—', '—', tag('unconfirmed · no PO/pack', 'w')]], sel=0) + card('382KY · price this', '<div class="grid g3"><div>' + kv([('Factory', 'Koso Tex · ₹186'), ('Similar confirmed', '375MC ₹181 · 440ON ₹179 · 382KT ₹184'), ('Suggested', '₹184 → $2.30 at 15% margin')]) + '</div><div>' + kv([('Buyer target', '$2.25 (from email 15 Sep)'), ('At target', 'margin 12.8% · above floor 12%'), ('Clock', 'Started at receipt 15 Sep 09:10')]) + '</div><div class="row" style="gap:6px;align-items:flex-start"><button class="btn sm">Send $2.30</button><button class="btn sm ghost">Send $2.25</button></div></div>', 'benchmark')),
 dict(slug='sampling', nav='sampling', title='Sampling · 631KX', crumb='Sampling › Nordic › Boys hoodie · rev 2', topbtn='<button class="btn ghost">Email buyer</button>&nbsp;<button class="btn">Send rev 3</button>',
  caption='Sample rounds with the buyer\'s comments read from email, the SLA anchored to the buyer\'s ask date, and the next sample due date computed — not remembered.',
  body='<div class="grid" style="grid-template-columns: 1.2fr 1fr">' + card('Rounds', timeline([('Proto · sent 22 Aug · approved with comments', 'lab dip approved', 'on'), ('Fit rev 1 · sent 05 Sep · comments 09 Sep', '"sleeve 2 cm longer"', 'on'), ('Fit rev 2 · sent 12 Sep · comments 15 Sep 22:14', '"neckline 1 cm wider" · read from email', 'on'), ('Fit rev 3 · due 19 Sep', 'SLA 14 d from ask (05 Sep) · 3 d left', 'cur'), ('Size set · Thu 25 Sep', 'factory ECC', ''), ('PP sample · 02 Oct', 'before bulk', '')])) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Buyer comment · 15 Sep 22:14', '<div class="doc" style="padding:12px 14px"><div>From: lars@nordicretail.se</div><div>Re: 631KX fit rev 2</div><div style="margin-top:6px;color:var(--ink)">Fit is good. Please make the <span class="mark">neckline 1 cm wider</span> and confirm <span class="mark">280 gsm</span> on the bulk fabric. Rev 3 by <span class="mark g">19 Sep</span> please.</div></div>' + '<div class="mono" style="margin-top:6px">Read: 1 change · due 19 Sep · gsm to confirm → 2 tasks</div>', 'email') + card('Tasks', lst([('Today', 'Send rev 2 comments to ECC · draft ready · Meena'), ('18 Sep', 'GSM test report 280 gsm · lab · Shridhar'), ('19 Sep', 'Rev 3 courier · AWB to buyer · Priya')])) + '</div></div>'),
 dict(slug='ta', nav='orders', title='Orders & T&A · PO 4471', crumb='Nordic Retail › 612KX · 12,000 · ETD 12 Oct', topbtn='<button class="btn ghost">Buyer view</button>&nbsp;<button class="btn ghost">Factory view</button>',
  caption='A time-and-action plan for every order, back-scheduled from the ship date across 28 stages, re-planned when a date moves — with skipped stages kept overdue until someone logs them.',
  body='<div class="grid" style="grid-template-columns: 1.5fr 1fr">' + card('T&A · 28 stages · re-planned 10:16', gantt([('Fabric in-house', 2, 14, 'done'), ('Lab dip', 4, 8, 'done'), ('Cutting', 16, 10, 'done'), ('Print', 26, 12, 'late'), ('Sewing', 40, 22, ''), ('Finishing', 62, 8, ''), ('Final inspection', 70, 4, ''), ('Ex-factory', 76, 3, ''), ('Handover', 80, 2, '')], ['1 Sep', '8', '15', '22', '29', '6 Oct', '13', '20', '27', '3 Nov'], etd=82) + '<div class="row" style="gap:14px;margin-top:6px"><span class="pill"><span class="dot g"></span>Done</span><span class="pill"><span class="dot" style="background:var(--ink)"></span>Planned</span><span class="pill"><span class="dot r"></span>Late / overdue</span><span class="pill"><span class="dot r" style="width:2px;height:12px;border-radius:0"></span>Handover 07 Oct</span></div>') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Print · overdue', kv([('Plan', '30 Sep'), ('Factory says', '06 Oct (AI call 09:38)'), ('If accepted', 'Sewing starts 07 Oct · handover 07 Oct holds · 1 d slack'), ('Chase history', 'WhatsApp +4 h, +24 h · AI call +36 h'), ('Rule', 'Stays overdue until logged — skipped stages are how orders go quiet')]) + '<div class="row" style="margin-top:6px"><button class="btn sm">Accept 06 Oct</button><button class="btn sm ghost">Push back</button></div>', 'decision') + card('Combos', table(['Combo', 'Qty', 'Stage'], [['03X Daisy', '#6,000', 'Print'], ['05X Minnie', '#6,000', 'Print']])) + '</div></div>'),
 dict(slug='inspection', nav='insp', title='Inspections · PO 4459', crumb='Final inspection · Laxmi Exports unit · Wed 10:00 · Uttarasami', fill=True,
  caption='Inspections logged on a phone at the factory: AQL sampling computed, defects photographed, pass/fail decided by the rule — and the report emailed to the buyer the same hour.',
  body='<div class="row top" style="gap:32px">' + phone('Final inspection · PO 4459', '309KU · 9,600 · AQL 2.5', '<div class="card" style="padding:12px 14px;gap:6px"><div class="row between"><b>Sample size</b><span class="tag">315 of 9,600</span></div><div style="font-size:12px;color:var(--ink2)">AQL 2.5 · general II · accept ≤ 14 major</div></div><div class="card" style="padding:12px 14px;gap:6px;border-color:var(--red)"><div class="row between"><b>Defects logged</b><span class="tag r">9 major · 21 minor</span></div><div style="font-size:12px">Broken stitch ×4 · Print misalign ×3 · Stain ×2</div><div class="row" style="gap:6px"><span class="chip">📷 12 photos</span><span class="chip">+ defect</span></div></div><div class="card" style="padding:12px 14px;gap:6px"><div class="row between"><b>Measurements</b><span class="tag g">12 / 12 in tolerance</span></div></div><div class="card flat" style="padding:12px 14px;gap:6px"><div class="row between"><b>Result</b><span class="tag g">PASS</span></div><div style="font-size:11.5px;color:var(--muted)">9 major ≤ 14 · report to buyer on submit</div><button class="btn sm">Submit &amp; email report</button></div>') + card('What submit does', timeline([('PDF report with photos · AQL working shown', 'generated', 'on'), ('Emailed to Nordic QA + Meena · logged on order', 'same hour', 'on'), ('Stage "Final inspection" marked done · handover clock starts', 'T&A', 'on'), ('Defect trend written to factory scorecard · Laxmi unit', 'reports', 'on'), ('If FAIL: re-inspection task + factory told with photos', 'rule', 'cur')]), 'no PDF typed', 'style="max-width:560px"') + '</div>'),
 dict(slug='shipments', nav='ship', title='Shipments', crumb='This month · 12 · sea + air', fill=True,
  caption='Handover, vessel, documents and the buyer\'s portal in one row per shipment — "on time" is judged at handover, which is the factory\'s clock, not the vessel\'s.',
  body=table(['Shipment', 'Buyer', 'POs', 'Handover', 'Vessel / flight', 'Docs', 'Status'], [['<b>VFEX-2291</b>', 'Nordic', '4459, 4462', '<b>On time</b> · 21 Sep', 'MSC Anna · ETD 26 Sep · Gothenburg', tag('4 / 5 · packing list', 'w'), tag('booking confirmed', 'g')], ['<b>VFEX-2290</b>', 'Koso', '4455', '<b>On time</b> · 19 Sep', 'Air · 20 Sep · ₹1.84 L approved', tag('5 / 5', 'g'), tag('gate pass', 'g')], ['<b>VFEX-2288</b>', 'Laxmi', '4441, 4442', 'Late 2 d · 12 Sep', 'MSC Lena · 15 Sep', tag('5 / 5', 'g'), tag('sailed', '')], ['<b>VFEX-2285</b>', 'Nordic', '4430', 'On time · 05 Sep', 'MSC Rita · 08 Sep', tag('5 / 5', 'g'), tag('arrived · portal updated', 'g')]]) + '<div class="grid g3">' + kpi('92%', 'handover on time · 30 d', ('was 71%', 'up')) + kpi('1', 'air freight this month', ('₹1.84 L · penalty avoided ₹4.2 L', '')) + kpi('0', 'documents re-typed', ('generated from the order', 'up')) + '</div>'),
 dict(slug='approvals', nav='appr', title='Approvals', crumb='3 waiting · plan dates, prices and money stop here', fill=True,
  caption='Plan-date changes, prices to buyers and invoices above PO wait for a named person. The AI shows the impact and recommends; a person decides.',
  body='<div style="display:flex;flex-direction:column;gap:12px">' + ''.join(f'<div class="card r" style="flex-direction:row;align-items:center;gap:18px"><div style="flex:1"><b>{t}</b><div style="color:var(--ink2);margin-top:2px">{d}</div><div class="mono" style="margin-top:6px">AI: {ai}</div></div><span class="mono">{w}</span><button class="btn sm">Approve</button><button class="btn sm ghost">Query</button></div>' for t, d, ai, w in [('Plan date change · PO 4468 · print end 30 Sep → 06 Oct', 'Requested via AI call to Ganesh · handover 07 Oct still holds with 1 day slack', 'accept; sewing on line 3 from 07 Oct; buyer not affected', 'Meena'), ('Price to buyer · 382KY · $2.30', 'Factory ₹186 · benchmark ₹181 · buyer target $2.25 · margin at target 12.8%', 'send $2.30 with a note on 180 gsm fabric; floor is 12%', 'Raja'), ('Fabric invoice DP/1183 · ₹186 vs PO ₹181.50', '1,960 kg received vs 2,000 billed', 'approve at PO rate for received qty; revised invoice requested', 'Accounts')]) + '</div>'),
]
