# Inventory & warehouse — Gupta Pipes (Lucknow) 3 godowns. Fictional.
from _lib import *
APP = dict(brand='StockSense', sub='Inventory & warehouse', client='Gupta Pipes', user='Anil Verma', role='Stores head',
  nav=[('home', 'Today', 'home', None), ('stock', 'Stock', 'box', None), ('bins', 'Bins & godowns', 'truck', None), ('moves', 'Movements', 'ladder', 'g24'), ('reorder', 'Reorder', 'cal', 5), ('count', 'Counts', 'check', None), ('-', 'Reports', '', None), ('reports', 'Reports', 'chart', None)],
  activity=[('11:20', '<b>GRN 2291</b> · 400 × 110mm SWR received at Godown A · scanned by Ramu'), ('10:48', '<b>Issue</b> · DO-26-1187 picked · 40 pipes + 120 elbows · Godown A'), ('10:02', '<b>Cycle count</b> · Bin B-14 · variance 0 · Sunita'), ('09:30', '<b>Reorder</b> · elbow 90mm below point · PO drafted to Prince Fittings'), ('06:00', '<b>Dead-stock report</b> · ₹38 L idle > 120 d · 3 suggestions')])
SCREENS = [
 dict(slug='today', nav='home', title='Today · 3 godowns', crumb='Tue 16 Sep · last sync 11:20',
  caption='Stock you can trust, in one view: value, idle stock with rupees attached, what is below reorder, and what moved since yesterday.',
  body=kpis([('₹2.8 Cr', 'stock value · 3 godowns', None), ('₹38 L', 'idle > 120 days', ('AI found buyers for ₹14 L', 'up'), 'r'), ('5', 'SKUs below reorder', ('POs drafted', '')), ('99.1%', 'count accuracy', ('was 91% before phones', 'up'))]) + '<div class="grid g2">' + card('Needs you', lst([('B-14', '<b>110mm SWR · 2,100 pcs idle 140 d</b> · Kanpur dealer Sharma asked for 400 this week · offer?', '<button class="btn sm">Offer</button>'), ('Reorder', '<b>Elbow 90mm below point</b> · 6-day lead · PO ₹1.2 L drafted to Prince Fittings', '<button class="btn sm ghost">Approve</button>'), ('Count', '<b>Godown C · bin C-07</b> · variance −38 pcs on Sunday count · recount?', '<button class="btn sm ghost">Assign</button>')]), '3') + card('By godown', table(['Godown', 'Value', 'Idle', 'Fill', 'Last count'], [['A · Lucknow (main)', '#₹1.6 Cr', '#₹19 L', '82%', 'Sun'], ['B · Kanpur', '#₹0.8 Cr', '#₹11 L', '64%', 'Sun'], ['C · Bareilly', '#₹0.4 Cr', '#₹8 L', '41%', 'Sat · variance']])) + '</div>'),
 dict(slug='stock', nav='stock', title='Stock', crumb='412 SKUs · all godowns', topbtn='<div class="chips"><span class="chip on">Idle > 90 d</span><span class="chip">Below reorder</span><span class="chip">Fast movers</span></div>',
  caption='Every SKU with age, value and velocity — and next to the dead stock, what the system suggests doing with it.',
  body=table(['SKU', 'Godown · bin', 'Qty', 'Value', 'Velocity', 'Age', 'Suggestion'], [['<b>SWR pipe 110mm × 3m</b>', 'A · B-14', '#2,100', '#₹18.9 L', '0 / month', tag('140 d', 'r'), 'Sharma Traders asked for 400 · Agarwal 250 → offer at 4% off'], ['<b>Agri pipe 75mm × 6m</b>', 'C · C-02', '#860', '#₹9.4 L', '12 / month', tag('118 d', 'r'), 'Season starts Oct · hold; move 300 to Godown A'], ['<b>Elbow 110mm</b>', 'A · B-03', '#640', '#₹1.9 L', '880 / month', tag('ok', 'g'), '—'], ['<b>Elbow 90mm</b>', 'A · B-04', '#120', '#₹0.3 L', '620 / month', tag('below reorder', 'w'), 'PO drafted · 1,500 pcs · Prince Fittings'], ['<b>CPVC 1" × 3m</b>', 'B · B-11', '#3,200', '#₹6.1 L', '410 / month', tag('ok', 'g'), '—'], ['<b>Solvent cement 500 ml</b>', 'A · A-09', '#48', '#₹0.1 L', '190 / month', tag('below reorder', 'w'), 'PO drafted · 300 · Astral']], sel=0)),
 dict(slug='bins', nav='bins', title='Bins · Godown A', crumb='Lucknow · 48 bins · scanned by phone', topbtn='<div class="chips"><span class="chip on">Fill</span><span class="chip">Age</span><span class="chip">Value</span></div>',
  caption='A live map of every bin: what is in it, how full, how old. Red is idle stock; amber is below reorder. Tap a bin to see its history.',
  body='<div class="grid" style="grid-template-columns: 1.5fr 1fr">' + card('Bin map', '<div class="grid" style="grid-template-columns: repeat(8, 1fr); gap: 8px">' + ''.join(f'<div class="card {c}" style="padding:10px;gap:4px;border-radius:9px"><div class="row between"><b style="font-size:12px">{b}</b><span class="mono" style="font-size:9px">{a}</span></div><div style="font-size:11px;color:var(--ink2);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{n}</div><div class="bar"><i class="{c or ""}" style="width:{w}%"></i></div></div>' for b, n, w, a, c in [('A-01', 'SWR 75mm', 80, '12 d', ''), ('A-02', 'SWR 90mm', 55, '8 d', ''), ('A-03', 'SWR 110mm', 90, '3 d', ''), ('A-04', 'SWR 160mm', 35, '21 d', ''), ('A-05', 'Agri 63mm', 70, '15 d', ''), ('A-06', 'Agri 75mm', 100, '118 d', 'r'), ('A-07', 'Agri 90mm', 60, '30 d', ''), ('A-08', 'CPVC 3/4"', 45, '6 d', ''), ('A-09', 'Solvent 500', 8, '2 d', 'w'), ('A-10', 'Solvent 1L', 40, '9 d', ''), ('B-01', 'Tee 110', 75, '4 d', ''), ('B-02', 'Tee 90', 66, '11 d', ''), ('B-03', 'Elbow 110', 58, '1 d', ''), ('B-04', 'Elbow 90', 10, '1 d', 'w'), ('B-05', 'Coupler 110', 82, '7 d', ''), ('B-06', 'Coupler 90', 64, '9 d', ''), ('B-07', 'Bend 110', 48, '18 d', ''), ('B-08', 'Trap 110', 30, '44 d', ''), ('B-09', 'Vent cowl', 92, '96 d', 'r'), ('B-10', 'Clamp 110', 70, '5 d', ''), ('B-11', 'CPVC 1"', 65, '6 d', ''), ('B-12', 'CPVC 1.5"', 50, '14 d', ''), ('B-13', 'Reducer', 44, '27 d', ''), ('B-14', 'SWR 110 ×3m', 100, '140 d', 'r')]) + '</div>', '24 of 48 shown') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Bin B-14', kv([('Item', 'SWR pipe 110mm × 3m'), ('Qty', '2,100 pcs · ₹18.9 L'), ('Received', '29 Apr · GRN 1740 · 2,400 pcs'), ('Issued', '300 · 12 May · last movement'), ('Idle', '140 days'), ('Counted', 'Sun 14 Sep · Sunita · variance 0')]), 'selected') + card('History', lst([('14 Sep', 'Cycle count · 2,100 · ok'), ('12 May', 'Issue 300 · DO-1102'), ('29 Apr', 'Receipt 2,400 · GRN 1740')])) + '</div></div>'),
 dict(slug='movements', nav='moves', title='Movements', crumb='Today · 24 · receipts, issues, transfers, returns', topbtn='<button class="btn ghost">Export</button>',
  caption='Receipts, issues, transfers and returns — every one scanned on a phone at the bin, timestamped, tied to a document. Nothing is typed twice.',
  body=table(['Time', 'Type', 'Item', 'Qty', 'From → to', 'Document', 'By', 'Check'], [['11:20', tag('receipt', 'g'), 'SWR 110mm × 3m', '#400', 'Truck → A · A-03', 'GRN 2291 · PO 1188', 'Ramu', tag('matches PO', 'g')], ['10:48', tag('issue', 'b'), 'SWR 110mm + elbows', '#40 + 120', 'A · A-03, B-03 → DO-1187', 'DO-26-1187', 'Ramu', tag('picked', 'g')], ['10:02', tag('count', ''), 'Vent cowl', '#—', 'B-09', 'Cycle count', 'Sunita', tag('variance 0', 'g')], ['09:40', tag('transfer', 'w'), 'Agri 75mm × 6m', '#300', 'C · C-02 → A · A-06', 'TR-118 · AI suggested', 'Anil', tag('in transit', 'w')], ['09:12', tag('return', 'r'), 'Elbow 110mm', '#4', 'Agarwal → A · B-03 (damaged)', 'CMP-2291', 'Ramu', tag('quarantine', 'r')], ['08:30', tag('issue', 'b'), 'CPVC 1"', '#120', 'B · B-11 → DO-1186', 'DO-26-1186', 'Mohan', tag('picked', 'g')]])),
 dict(slug='reorder', nav='reorder', title='Reorder', crumb='5 SKUs below point · POs drafted from lead times and velocity', topbtn='<button class="btn">Approve all</button>',
  caption='Reorder points that learn from velocity and lead time, and POs drafted for you — sent to the vendor on WhatsApp the moment you approve.',
  body=table(['SKU', 'On hand', 'Point', 'Velocity', 'Lead time', 'Suggested qty', 'Vendor', 'PO'], [['<b>Elbow 90mm</b>', '#120', '#400', '620 / mo', '6 d', '#1,500', 'Prince Fittings · ₹1.2 L', '<button class="btn sm">Approve</button>'], ['<b>Solvent cement 500 ml</b>', '#48', '#120', '190 / mo', '4 d', '#300', 'Astral · ₹0.3 L', '<button class="btn sm">Approve</button>'], ['<b>Clamp 90mm</b>', '#210', '#300', '340 / mo', '5 d', '#800', 'Prince Fittings · ₹0.4 L', '<button class="btn sm">Approve</button>'], ['<b>Tee 75mm</b>', '#90', '#150', '160 / mo', '6 d', '#400', 'Prince Fittings · ₹0.5 L', '<button class="btn sm">Approve</button>'], ['<b>Trap 110mm</b>', '#60', '#80', '70 / mo', '9 d', '#200', 'Own plant', '<button class="btn sm ghost">Plan</button>']]) + '<div class="grid g2">' + card('How the point is set', kv([('Formula', 'lead time × daily velocity × 1.3 safety'), ('Velocity', '90-day weighted, seasonality from last year'), ('Learns', 'Point drifts when velocity changes 2 months in a row'), ('Override', 'Any point can be pinned by Anil')])) + card('Sent to vendor · WhatsApp', wa('Prince Fittings · Rajesh', 'Vendor · Kanpur', [('me', 'PO GP/1189: Elbow 90mm × 1,500, Clamp 90mm × 800, Tee 75mm × 400. Deliver by 22 Sep to Lucknow. Please confirm.', '11:32 · auto'), ('', 'Confirmed sir, 21 Sep dispatch', '11:40'), ('sys', 'Vendor confirmed 21 Sep · expected receipt 22 Sep · GRN pre-created')], av='PF')) + '</div>'),
 dict(slug='count', nav='count', title='Counts · phone', crumb='Cycle count · Godown C · Sunita · Sat 09:10',
  caption='Counting on a phone, bin by bin, with the expected quantity hidden until the count is entered — variances explained on the spot, no clipboard.',
  body='<div class="row top" style="gap:32px">' + phone('Cycle count · Godown C', '12 bins today · 9 done', '<div class="card" style="padding:12px 14px;gap:6px;border-color:var(--red)"><div class="row between"><b>Bin C-07 · SWR 160mm</b><span class="tag r">variance</span></div><div class="kv" style="grid-template-columns:90px 1fr"><span class="k">Counted</span><span><b>202</b></span><span class="k">Expected</span><span>240</span><span class="k">Variance</span><span style="color:var(--red)"><b>−38</b> · ₹68,400</span></div><div class="fld"><label>Reason</label><div class="in sel">Issued without scan?</div></div><div class="row" style="gap:6px"><button class="btn sm">Recount</button><button class="btn sm ghost">Submit</button></div></div><div class="card" style="padding:12px 14px;gap:4px"><div class="row between"><b>C-06 · SWR 110mm</b><span class="tag g">0</span></div><div style="font-size:11.5px;color:var(--muted)">184 counted · 09:04</div></div><div class="card" style="padding:12px 14px;gap:4px"><div class="row between"><b>C-05 · Agri 90mm</b><span class="tag g">0</span></div><div style="font-size:11.5px;color:var(--muted)">310 counted · 08:58</div></div><div class="card flat" style="padding:10px 12px;font-size:11.5px;color:var(--muted)">Expected qty hidden until you count. Photo optional.</div>') + card('Variance C-07 · what the system checked', timeline([('Last count 240 · 24 Aug · Sunita', 'baseline', 'on'), ('Issues since: DO-1151 (20), DO-1163 (18) — both scanned', 'accounted', 'on'), ('One issue on 02 Sep has no scan: DO-1158 · 40 pcs · Bareilly', 'likely cause', 'on'), ('Suggest: post DO-1158 issue · variance becomes +2', 'Anil to confirm', 'cur')]) + '<div class="row" style="margin-top:8px"><button class="btn sm">Post DO-1158</button><button class="btn sm ghost">Recount first</button></div>', 'explained', 'style="max-width:560px"') + '</div>'),
 dict(slug='reports', nav='reports', title='Reports', crumb='Sep 2026 · 3 godowns', fill=True, topbtn='<div class="chips"><span class="chip">Week</span><span class="chip on">Month</span><span class="chip">Quarter</span></div>',
  caption='Ageing, turns, accuracy and the rupees recovered from dead stock — compiled every night, sent to the owner every Monday.',
  body=kpis([('4.2×', 'stock turns · annualised', ('was 3.1×', 'up')), ('₹14 L', 'dead stock sold / used', ('this month', 'up'), 'r'), ('99.1%', 'count accuracy', ('+8 pts since phones', 'up')), ('0', 'stock-outs on fast movers', ('was 6 / month', 'up'))]) + '<div class="grid g2">' + card('Stock ageing · value', bars([(100, 'g'), (70, ''), (40, ''), (28, 'r'), (22, 'r'), (14, 'r')]) + '<div class="row between mono"><span>0–30 d</span><span>31–60</span><span>61–90</span><span>91–120</span><span>121–180</span><span>180+</span></div>') + card('Dead stock · what happened to it', hbars([('Sold to dealers (offers)', 100, '₹9.1 L', 'g'), ('Used on orders (AI match)', 55, '₹5.0 L', 'g'), ('Transferred to a moving godown', 30, '₹2.7 L', ''), ('Still idle', 100, '₹24 L', 'r')])) + '</div>'),
]
