# Manufacturing ERP — Deccan Protective Products (Pune). Fictional.
from _lib import *
APP = dict(brand='PlantOS', sub='Manufacturing ERP', client='Deccan Protective', user='Suresh K', role='Plant head',
  nav=[('home', 'Today', 'home', None), ('orders', 'Orders', 'box', None), ('plan', 'Planning', 'cal', None), ('stock', 'Inventory', 'truck', 'g7'), ('cost', 'Cost estimation', 'rupee', None), ('vendors', 'Vendors & portal', 'users', None), ('-', 'Control', '', None), ('appr', 'Approvals', 'check', 3), ('reports', 'Reports', 'chart', None)],
  activity=[('09:41', '<b>SO 2291</b> · material shortfall 380 kg ABS flagged · PO drafted to Deccan Polymers'), ('09:12', '<b>Line 3</b> · maintenance ticket MT-118 opened · 2 orders re-planned'), ('08:55', '<b>GRN 1183</b> · 1,960 kg ABS received · invoice held (rate)'), ('08:30', '<b>SO 2270</b> · gate pass issued · dispatch Thu · customer notified'), ('06:00', '<b>Owner digest</b> sent · 4 decisions listed')])
SCREENS = [
 dict(slug='today', nav='home', title='Today · Plant 2', crumb='Tue 16 Sep · compiled 06:00',
  caption='The plant head\'s morning: order book by stage, what will miss its date, idle stock with rupees attached, and the four decisions only he can take.',
  body=kpis([('₹18.4 Cr', 'open order book', ('142 orders', '')), ('6', 'orders will miss OTIF', ('was 9 · 8-day warning', 'up'), 'r'), ('₹3.1 Cr', 'stock idle > 90 days', ('12% of value', 'dn')), ('96.2%', 'OTIF · 30 days', ('+4.1 pts', 'up'))]) + '<div class="grid g2">' + card('Needs you', lst([('SO 2291', '<b>Safety helmets · 5,000</b> · ABS shell short by 380 kg · buy at ₹186 (Deccan Polymers) or shift 2 days?', '<button class="btn sm">Decide</button>'), ('Line 3', '<b>Injection m/c 3 downtime 6 h</b> yesterday · maintenance ticket open · 2 orders affected', '<button class="btn sm ghost">Open</button>'), ('Invoice', '<b>₹186 vs PO ₹181.50</b> · 1,960 kg · Accounts asks you', '<button class="btn sm ghost">Review</button>'), ('Dead stock', '<b>₹42 L</b> · reflective tape · no order in 140 days · AI suggests 2 buyers', '<button class="btn sm ghost">See</button>')]), '4') + card('Order book by stage', hbars([('Raw material', 22, '31', ''), ('Moulding', 38, '54', ''), ('Assembly', 20, '28', ''), ('Testing', 9, '13', ''), ('Packing', 7, '10', ''), ('Dispatch', 4, '6', 'g')]) + '<div class="mono">142 live · 3 plants · 11 product families</div>') + '</div>'),
 dict(slug='orders', nav='orders', title='Orders', crumb='142 live · sorted by promised date', topbtn='<div class="chips"><span class="chip on">All</span><span class="chip">Will miss</span><span class="chip">This week</span><span class="chip">Govt tenders</span></div>',
  caption='Every order with its promised date, stage, material readiness and risk — the risk computed from the plan, not typed by a planner.',
  body=table(['SO', 'Customer', 'Product', 'Qty', 'Promised', 'Stage', 'Material', 'Risk'], [['<b>SO 2291</b>', 'Bharat Rail · tender', 'Safety helmet ABS · white', '#5,000', '02 Oct', 'Moulding', tag('short 380 kg', 'r'), tag('will miss 2 d', 'r')], ['<b>SO 2288</b>', 'Tata Projects', 'Safety goggles', '#12,000', '28 Sep', 'Assembly', tag('ok', 'g'), tag('on track', 'g')], ['<b>SO 2284</b>', 'L&amp;T · Mumbai', 'Reflective vests', '#8,000', '25 Sep', 'Testing', tag('ok', 'g'), tag('on track', 'g')], ['<b>SO 2279</b>', 'Adani · Mundra', 'Ear muffs', '#3,000', '24 Sep', 'Packing', tag('ok', 'g'), tag('dispatch Thu', 'g')], ['<b>SO 2275</b>', 'Distributor · Nagpur', 'Helmet · yellow', '#2,400', '22 Sep', 'Moulding', tag('ok', 'g'), tag('1 day slack', 'w')], ['<b>SO 2270</b>', 'JSW · Bellary', 'Face shields', '#6,000', '20 Sep', 'Dispatch', tag('ok', 'g'), tag('gate pass', 'g')]], sel=0)),
 dict(slug='planning', fill=True, nav='plan', title='Planning board · Week 39', crumb='Plant 2 · 4 lines · capacity 92%', topbtn='<button class="btn ghost">Re-plan</button>&nbsp;<button class="btn">Freeze week</button>',
  caption='Capacity, changeovers and priorities on one board. Drag an order and the system tells you what else moves — and which promise breaks.',
  body='<div class="grid" style="grid-template-columns: 1.5fr 1fr">' + card('Lines × days', gantt([('Line 1 · helmets', 0, 45, 'done'), ('Line 1 · helmets', 46, 40, ''), ('Line 2 · goggles', 0, 60, 'done'), ('Line 2 · vests', 62, 30, ''), ('Line 3 · ear muffs', 0, 25, 'done'), ('Line 3 · ⚠ downtime', 26, 8, 'late'), ('Line 3 · helmets yellow', 36, 50, ''), ('Line 4 · face shields', 0, 90, '')], ['Mon 22', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Mon 29', 'Tue', 'Wed', 'Thu'], etd=70), 'changeovers: 5 · 3.5 h') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('If SO 2291 moves to Line 3', kv([('Line 3', 'Helmets yellow (SO 2275) pushed 1 day'), ('SO 2275', 'Still 0 days slack → at risk'), ('SO 2291', 'On time · 02 Oct'), ('Changeovers', '+1 (colour) · 40 min')]) + '<div class="row"><button class="btn sm">Apply</button><button class="btn sm ghost">Try another</button></div>', 'what-if') + card('Material for the week', hbars([('ABS granules', 78, '78%', 'w'), ('PC sheet', 100, '100%', 'g'), ('Foam liner', 100, '100%', 'g'), ('Reflective tape', 100, '340%', 'r')]) + '<div class="mono">Reflective tape: 3.4× the week\'s need in stock → idle</div>') + '</div></div>'),
 dict(slug='inventory', nav='stock', title='Inventory · Plant 2 store', crumb='1,240 SKUs · counted by phone · last full count Sun', topbtn='<div class="chips"><span class="chip">All</span><span class="chip on">Idle > 90 d</span><span class="chip">Below reorder</span></div>',
  caption='Stock you can trust, and dead stock with the rupees attached — every bin aged and valued, receipts and issues scanned on a phone.',
  body=kpis([('₹6.4 Cr', 'stock value', None), ('₹3.1 Cr', 'idle > 90 days', ('AI found a use for ₹1.2 Cr', 'up'), 'r'), ('7', 'SKUs below reorder', ('POs drafted', '')), ('98.2%', 'count accuracy', ('+2.1 pts', 'up'))]) + table(['SKU', 'Bin', 'Qty', 'Value', 'Last used', 'Age', 'AI suggestion'], [['<b>Reflective tape 50mm · silver</b>', 'B-14', '#12,400 m', '#₹42 L', '140 d ago', tag('idle', 'r'), 'Use on SO 2284 vests (needs 2,100 m) · offer 8,000 m to Nagpur distributor'], ['<b>ABS granules · white</b>', 'A-02', '#1,620 kg', '#₹3.0 L', 'today', tag('short', 'w'), 'Short 380 kg for SO 2291 · PO drafted to Deccan Polymers'], ['<b>PC sheet 1.5mm</b>', 'C-07', '#3,900 sq m', '#₹28 L', '95 d ago', tag('idle', 'r'), 'Covers 2 quarters of face-shield demand · pause reorder'], ['<b>Foam liner · grey</b>', 'B-03', '#22,000', '#₹6.6 L', 'yesterday', tag('ok', 'g'), '—'], ['<b>Elastic strap 25mm</b>', 'B-09', '#800 m', '#₹0.4 L', 'today', tag('reorder', 'w'), 'Below reorder (1,500 m) · lead time 6 d · PO drafted']], sel=0)),
 dict(slug='costing', fill=True, nav='cost', title='Cost estimation · Safety helmet ABS · 5,000', crumb='Estimates › Bharat Rail tender › rev 3', topbtn='<button class="btn ghost">Compare rev 2</button>&nbsp;<button class="btn">Send quote</button>',
  caption='A costing model that shows its working — materials, cycle time, changeovers, packing — learns from what the run actually consumed, and flags what changed since the last quote.',
  body='<div class="grid" style="grid-template-columns: 1.4fr 1fr">' + card('Estimate', table(['Line', 'Basis', 'Rate', 'Per unit', 'vs rev 2'], [['ABS granules · 0.42 kg', 'actual avg last 3 runs: 0.418 kg', '₹186 / kg', '#₹78.12', '<span style="color:var(--red)">+₹3.40 (rate ↑)</span>'], ['Suspension &amp; strap set', 'BOM', '₹31.00', '#₹31.00', '—'], ['Moulding · 38 s cycle', 'measured · m/c 3', '₹640 / hr', '#₹6.76', '<span style="color:var(--ok)">−₹0.40 (cycle ↓)</span>'], ['Changeover · amortised', '1 colour change / 5,000', '₹4,200', '#₹0.84', 'quantified for the first time'], ['Testing &amp; packing', 'std', '—', '#₹4.10', '—'], ['<b>Cost per unit</b>', '', '', '#<b>₹120.82</b>', '<b style="color:var(--red)">+2.5% vs rev 2</b>']]), 'rev 3 · 16 Sep') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Quote', kv([('Cost', '₹120.82'), ('Margin', '18% → <b>₹142.57</b>'), ('Tender L1 (last)', '₹139.00'), ('At L1', 'margin 15.0% · still above floor 12%')]) + '<div class="row" style="margin-top:6px"><button class="btn sm">Quote ₹139.00</button><button class="btn sm ghost">Hold 18%</button></div>', 'decision') + card('Learned from runs', lst([('Sep', 'ABS actual 0.418 kg/unit vs 0.45 assumed → model updated'), ('Aug', 'Cycle 38 s on m/c 3 vs 40 s std'), ('Jul', 'Changeover cost was never in the sheet · added')]), 'writes back') + '</div></div>'),
 dict(slug='vendors', fill=True, nav='vendors', title='Vendors & portal', crumb='42 vendors · 9 on portal · payment questions answered without a call', topbtn='<button class="btn">Invite vendor</button>',
  caption='A vendor portal that answers "when is my payment?" — plus POs, GRNs, invoice status and rate disputes, so the phone stops ringing at accounts.',
  body='<div class="grid" style="grid-template-columns: 1fr 1.2fr">' + card('Vendor view · Deccan Polymers', kv([('Open POs', '2 · ₹9.4 L'), ('GRN pending', 'PO 4471 · 1,960 kg received 15 Sep'), ('Invoice DP/1183', '<span class="tag w">held · rate mismatch</span>'), ('Next payment', 'DP/1172 · ₹3.2 L · Fri 19 Sep'), ('Ledger', 'balance ₹6.1 L · 0 overdue')]) + '<div class="mono" style="margin-top:6px">What the vendor sees on their phone — no calls to accounts</div>', 'portal') + card('Payment questions · this month', hbars([('Answered on portal', 100, '184', 'g'), ('Answered on WhatsApp bot', 61, '112', ''), ('Reached accounts by phone', 12, '22', 'r')]) + table(['Vendor', 'On portal', 'Open POs', 'Invoices held', 'Calls to accounts'], [['Deccan Polymers', tag('yes', 'g'), '#2', '#1', '#0'], ['Shree Foam', tag('yes', 'g'), '#1', '#0', '#0'], ['Verma Roadways', tag('no', ''), '#—', '#2', '#6'], ['Kiran Plastics', tag('invited', 'b'), '#3', '#0', '#4']]), '75% fewer calls') + '</div>'),
 dict(slug='approvals', nav='appr', title='Approvals', crumb='3 waiting · anything that costs money stops here', 
  caption='Nothing moves money without a person. Invoices above PO, plan-date changes and freight decisions queue here with the working shown and the AI\'s recommendation.',
  body='<div style="display:flex;flex-direction:column;gap:12px">' + ''.join(f'<div class="card r" style="flex-direction:row;align-items:center;gap:18px"><div style="flex:1"><b>{t}</b><div style="color:var(--ink2);margin-top:2px">{d}</div><div class="mono" style="margin-top:6px">AI: {ai}</div></div><span class="mono">{w}</span><button class="btn sm">Approve</button><button class="btn sm ghost">Query</button></div>' for t, d, ai, w in [('Fabric invoice DP/26-27/1183 · Deccan Polymers', 'Rate ₹186 vs PO ₹181.50 · 1,960 kg received vs 2,000 billed · difference ₹8,820 + GST', 'accept at PO rate for 1,960 kg (₹3,55,740) and ask for a revised invoice — draft ready', 'Accounts'), ('Plan date change · SO 2291', 'Moulding end 30 Sep → 02 Oct · requested by Line 1 supervisor · promise to Bharat Rail still holds by 1 day', 'accept; move SO 2275 to Line 3 to recover slack (what-if attached)', 'Planning'), ('Express freight · SO 2270', '₹1.84 L to reach Bellary by 20 Sep · surface would miss by 3 days · customer is JSW (top 5)', 'approve — penalty clause ₹4.2 L exceeds freight; note for next quote', 'Logistics')]) + '</div>' + card('Approved this month', table(['When', 'What', 'By', 'Posted to'], [['15 Sep', 'Vendor invoice · Shree Foam · ₹2.1 L', 'Uma', 'Tally · ok'], ['14 Sep', 'Plan change · SO 2284 · +1 day', 'Suresh', 'Plan · customer notified'], ['12 Sep', 'Reorder · elastic strap · ₹0.9 L', 'Suresh', 'PO sent · portal']]), '31 · avg 4 h to decision')),
]
