# MIS dashboards — Annapoorna Group (Trichy), 7 outlets. Fictional.
from _lib import *
APP = dict(brand='OwnerView', sub='MIS dashboards', client='Annapoorna Group', user='Karthik A', role='Owner',
  nav=[('home', 'Owner view', 'home', None), ('outlets', 'Outlets', 'board', None), ('gov', 'Governance', 'bell', 3), ('collect', 'Collectors', 'phone', None), ('digest', 'Digests', 'doc', None), ('-', 'Setup', '', None), ('kpis', 'KPIs & weights', 'cog', None), ('reports', 'Reports', 'chart', None)],
  activity=[('12:04', '<b>Thillai Nagar</b> · wastage question overdue → escalated to Ramesh'), ('11:15', '<b>Checklists</b> · 6 of 7 submitted · Srirangam reminded'), ('06:00', '<b>Compile</b> · 7 outlets scored · 2 flags · digest sent'), ('Yesterday', '<b>Cantonment</b> · billing variance ₹4,100 · 2 voids · question to cashier lead'), ('Mon', '<b>Weekly</b> · P&amp;L per outlet compiled from POS + Tally')])
SCREENS = [
 dict(slug='owner', nav='home', title='Owner view', crumb='Tue 16 Sep · compiled 06:00 · 7 outlets',
  caption='One screen the owner actually opens: each outlet scored from real inputs — POS, checklists, attendance, Tally — with the questions already sent to the right people.',
  body=kpis([('₹6.4 L', 'sales yesterday', ('+4% vs last Tue', 'up')), ('5 / 7', 'outlets normal', ('2 flagged', ''), 'r'), ('3', 'governance questions open', ('1 overdue', 'dn')), ('6.1%', 'worst wastage · Thillai Nagar', ('limit 5%', 'dn'))]) + '<div class="grid" style="grid-template-columns: 1.3fr 1fr">' + card('Outlets · score', '<div class="grid g4" style="gap:8px">' + ''.join(f'<div class="card {c}" style="padding:12px 14px;gap:4px"><div class="row between"><b>{n}</b><span class="tag {t}">{s}</span></div><div style="font-size:11.5px;color:var(--ink2)">{d}</div></div>' for n, s, t, d, c in [('Cantonment', 72, 'w', 'billing variance ₹4,100 · 1 complaint', 'r'), ('Thillai Nagar', 68, 'r', 'wastage 6.1% · 2nd time', 'r'), ('Srirangam', '—', '', 'checklist not submitted', 'flat'), ('Central bus stand', 88, 'g', 'punctuality trend · watch', ''), ('Banquets', 94, 'g', 'normal', ''), ('Woraiyur', 91, 'g', 'normal', ''), ('Central kitchen', 90, 'g', 'normal', ''), ('Group', 86, 'g', 'weighted', 'flat')]) + '</div>') + card('Questions sent · who · by when', lst([('12:00', '<b>Senthil</b> (Thillai Nagar) — "What was wasted and why?" · photo required', tag('overdue → Ramesh', 'r')), ('13:00', '<b>Devi</b> (Cantonment) — call the guest back; log outcome', tag('due', 'w')), ('Today', '<b>Prakash</b> (cashier lead) — "Which bills were voided and why?"', tag('answered 11:20', 'g')), ('Week', '<b>HR</b> — roster review · Central bus stand', tag('watch', ''))]), 'governance') + '</div>'),
 dict(slug='outlet', nav='outlets', title='Outlet · Thillai Nagar', crumb='Outlets › Thillai Nagar · score 68 · manager Senthil',
  caption='Drill into one outlet: every KPI with its source and weight, the trend, and the chain of questions that a breach triggered.',
  body='<div class="grid g4">' + kpi('₹78,400', 'sales yesterday', ('−6% vs avg Tue', 'dn')) + kpi('6.1%', 'wastage', ('limit 5.0%', 'dn'), 'r') + kpi('2', 'late arrivals', ('limit 3', '')) + kpi('0', 'complaints', None) + '</div><div class="grid g2">' + card('Score 68 · how it is made', table(['KPI', 'Value', 'Source', 'Weight', 'Points'], [['Sales vs plan', '94%', 'POS', '25', '#22'], ['Wastage', '6.1%', 'Checklist + consumption', '20', '#8'], ['Hygiene checklist', '17 / 18', 'Phone checklist · 07:10', '15', '#14'], ['Punctuality', '2 late', 'Biometric', '15', '#13'], ['Billing variance', '₹340', 'POS vs cash', '15', '#15'], ['Complaints', '0', 'WhatsApp + book', '10', '#10']])) + card('Wastage · 14 days', bars([(50, ''), (52, ''), (48, ''), (58, 'r'), (46, ''), (44, ''), (50, ''), (49, ''), (53, ''), (47, ''), (55, ''), (51, ''), (61, 'r'), (61, 'r')]) + '<div class="row between mono"><span>03 Sep</span><span>limit 5.0%</span><span>16 Sep</span></div>' + '<div class="list"><div><span class="t">06:11</span>Question sent to Senthil · due 12:00</div><div><span class="t">12:04</span>No reply · escalated to Ramesh with the 04 Sep breach</div></div>') + '</div>'),
 dict(slug='governance', nav='gov', title='Governance', crumb='threshold → question → owner → deadline · 3 open', fill=True,
  caption='Governance rules turn a number into a question to a named person with a deadline — and an escalation when the deadline passes. The owner sees the exceptions, not the spreadsheet.',
  body='<div class="grid" style="grid-template-columns: 1.3fr 1fr">' + table(['Rule', 'Threshold', 'Question to', 'Deadline', 'Escalates to', 'Fired · 30 d'], [['<b>Wastage</b>', '> 5%', 'Outlet manager · photo of log', '6 h', 'Area → Ops head', '#38'], ['<b>Billing variance</b>', '> ₹2,000 / shift', 'Cashier lead · void log', 'same day', 'Outlet manager → Owner', '#11'], ['<b>Checklist missing</b>', 'by 11:00', 'Outlet manager', '2 reminders', 'Area manager', '#9'], ['<b>Guest complaint</b>', 'any', 'Outlet manager · call back', '2 h', 'Ops head', '#14'], ['<b>Punctuality</b>', '≥ 3 late / 3 days', 'HR · roster', 'week', '—', '#6'], ['<b>Sales drop</b>', '< 85% of plan · 3 days', 'Outlet manager · reason', '1 day', 'Owner', '#4']]) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Open now', lst([('12:04', '<b>Wastage · Thillai Nagar</b> · overdue → Ramesh', tag('escalated', 'r')), ('13:00', '<b>Complaint · Cantonment</b> · Devi to call', tag('due', 'w')), ('Week', '<b>Punctuality · Central</b> · HR', tag('watch', ''))]), '3') + card('Answered · 30 days', hbars([('Questions sent', 100, '82', ''), ('Answered by deadline', 74, '61', 'g'), ('Escalated', 26, '21', 'r'), ('Led to a change', 34, '28', '')])) + '</div></div>'),
 dict(slug='collectors', nav='collect', title='Collectors', crumb='Where the numbers come from · nothing typed into a report', fill=True,
  caption='Numbers are collected, not typed: phone checklists, POS and Tally connectors, attendance, WhatsApp — compiled every night into the formats the owner already uses.',
  body='<div class="grid" style="grid-template-columns: 1fr 1.3fr">' + phone('Opening checklist · Woraiyur', 'Mon 07:10 · Kumar', '<div class="card" style="padding:10px 12px;gap:6px"><div class="row between"><b>Hygiene</b><span class="tag g">6 / 6</span></div><div style="font-size:11.5px;color:var(--ink2)">Floor · counters · fridge temp 3°C · 📷</div></div><div class="card" style="padding:10px 12px;gap:6px"><div class="row between"><b>Stock on hand</b><span class="tag">4 items</span></div><div style="font-size:11.5px;color:var(--ink2)">Rice 42 kg · Oil 18 L · Dal 11 kg · Milk 36 L</div></div><div class="card" style="padding:10px 12px;gap:6px;border-color:var(--red)"><div class="row between"><b>Wastage log</b><span class="tag r">required</span></div><div class="fld"><label>Yesterday\'s wastage</label><div class="in">2.4 kg cooked rice · 📷</div></div></div><div class="card flat" style="padding:10px 12px;font-size:11.5px;color:var(--muted)">2 min · submitted 07:14 · offline OK</div>') + table(['Collector', 'Type', 'Feeds', 'Frequency', 'Last', 'Health'], [['<b>Phone checklists</b>', 'App · 7 outlets', 'Hygiene, wastage, stock, punctuality', 'Daily 07:00', '11:15 · 6 / 7', tag('1 missing', 'w')], ['<b>POS</b>', 'Connector', 'Sales, voids, discounts, covers', 'Every 15 min', '11:58', tag('ok', 'g')], ['<b>Tally</b>', 'Connector', 'Purchases, payments, P&amp;L', 'Nightly', '02:00', tag('ok', 'g')], ['<b>Biometric</b>', 'Connector', 'Attendance, late arrivals', 'Hourly', '11:00', tag('ok', 'g')], ['<b>WhatsApp</b>', 'Number', 'Complaints, answers to questions', 'Live', 'live', tag('ok', 'g')], ['<b>Purchase sheet</b>', 'Google Sheet', 'Requests, PO log', 'Live', '10:30', tag('ok', 'g')]]) + '</div>'),
 dict(slug='digest', nav='digest', title='Digests', crumb='Owner · 06:00 · and one per role', fill=True, topbtn='<div class="chips"><span class="chip on">Owner</span><span class="chip">Ops head</span><span class="chip">Outlet managers</span></div>',
  caption='The digest is the product for most owners: five lines a day, each with a number, a person and a deadline, and a reply that opens the detail.',
  body='<div class="grid g2">' + digest('☀ Annapoorna · Tue 16 Sep', ['<b>Five outlets normal.</b> Cantonment scored 72 — billing variance ₹4,100 on two shifts, one guest complaint (billing). Prakash answered on the voids; Devi calls the guest by 13:00.', '<b>Thillai Nagar 68</b> — wastage 6.1% (limit 5%), 2nd time in 14 days. Senthil asked by 12:00.', '<b>Srirangam</b> — checklist not submitted by 11:00; reminded twice.', '<b>Sales</b> — ₹6.4 L yesterday, +4% vs last Tue; Banquets ₹1.1 L.', '<b>Spend</b> — ₹1.9 L through approvals; 0 outside policy.', '<span class="mono">Reply 1 · Cantonment voids · 2 · Thillai Nagar history · 3 · weekly P&amp;L</span>']) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Owner replied "2" · 06:40', wa('OwnerView', 'digest', [('me', '2', '06:40'), ('', 'Thillai Nagar · wastage 14 d: avg 5.1% · breaches 04 Sep (5.8%), 16 Sep (6.1%) · both Fridays\' prep over-ordered · Senthil\'s 04 Sep reason: "event cancelled". Suggest: cap Friday prep at 90% of forecast.', '06:40'), ('me', 'Do it. Tell Senthil.', '06:41'), ('', 'Rule added · Senthil told · Ramesh copied.', '06:41')], av='OV')) + card('Digests · 30 days', hbars([('Sent', 100, '30', ''), ('Opened within 1 h', 97, '29', 'g'), ('Replied', 53, '16', ''), ('Led to a rule change', 13, '4', 'r')])) + '</div></div>'),
 dict(slug='kpis', nav='kpis', title='KPIs & weights', crumb='Score = Σ weight × band · set by the owner', fill=True, topbtn='<button class="btn">Save</button>',
  caption='The owner sets what matters and how much: KPIs, their sources, weights and thresholds — the compile does the rest, every night, for every outlet.',
  body=table(['KPI', 'Source', 'Weight', 'Green', 'Amber', 'Red', 'Question goes to'], [['Sales vs plan', 'POS', '#25', '≥ 95%', '85–95%', '< 85% · 3 d', 'Outlet manager'], ['Wastage', 'Checklist ÷ consumption', '#20', '≤ 4%', '4–5%', '> 5%', 'Outlet manager · photo'], ['Hygiene checklist', 'Phone · 18 items', '#15', '18 / 18', '16–17', '≤ 15', 'Outlet manager'], ['Punctuality', 'Biometric', '#15', '0 late', '1–2', '≥ 3 / 3 d', 'HR'], ['Billing variance', 'POS vs cash', '#15', '< ₹500', '₹500–2,000', '> ₹2,000', 'Cashier lead'], ['Complaints', 'WhatsApp + book', '#10', '0', '1', '≥ 2', 'Outlet manager · call back']]) + '<div class="grid g2">' + card('Weights · by outlet type', switches([('Banquets: sales weight 35, wastage 10', True), ('Central kitchen: wastage 30, sales 10', True), ('New outlets: no score for first 30 days', True)])) + card('Formats', kv([('Owner', 'WhatsApp digest 06:00 · Excel weekly'), ('Ops head', 'Dashboard + questions'), ('Outlet managers', 'Own outlet only · phone'), ('Accountant', 'Power BI blueprint · Tally')])) + '</div>'),
 dict(slug='reports', nav='reports', title='Reports · weekly P&amp;L', crumb='Week 37 · per outlet · from POS + Tally', fill=True,
  caption='The weekly P&L per outlet that used to take an accountant two days — compiled from POS and Tally on Sunday night, in the owner\'s own format.',
  body=table(['Outlet', 'Sales', 'Food cost', 'Staff', 'Rent & utilities', 'Wastage', 'Net', 'Margin'], [['Cantonment', '#₹6.2 L', '#34%', '#22%', '#11%', '#4.1%', '#₹1.7 L', '#27%'], ['Thillai Nagar', '#₹5.4 L', '#37%', '#24%', '#12%', '#5.6%', '#₹1.1 L', '#20%'], ['Srirangam', '#₹4.1 L', '#35%', '#25%', '#14%', '#4.4%', '#₹0.8 L', '#19%'], ['Central bus stand', '#₹7.8 L', '#33%', '#20%', '#9%', '#3.9%', '#₹2.7 L', '#35%'], ['Banquets', '#₹9.6 L', '#31%', '#18%', '#8%', '#3.2%', '#₹3.8 L', '#40%'], ['Woraiyur', '#₹4.8 L', '#34%', '#23%', '#12%', '#4.0%', '#₹1.3 L', '#27%'], ['<b>Group</b>', '#<b>₹37.9 L</b>', '#<b>34%</b>', '#<b>21%</b>', '#<b>11%</b>', '#<b>4.2%</b>', '#<b>₹11.4 L</b>', '#<b>30%</b>']]) + '<div class="grid g3">' + kpi('2 days → 0', 'accountant time per week', ('compiled Sunday 23:00', 'up')) + kpi('₹1.2 L', 'wastage this week', ('Thillai Nagar 41% of it', 'dn'), 'r') + kpi('100%', 'lines traceable to a source', None) + '</div>'),
]
