# Real-estate CRM with AI calling — Shubham Developers (Surat). Fictional.
from _lib import *
APP = dict(brand='SiteDesk', sub='Real-estate CRM', client='Shubham Developers', user='Vikram Shah', role='Sales head',
  nav=[('home', 'Today', 'home', None), ('leads', 'Leads', 'users', 22), ('board', 'Pipeline', 'board', None), ('visits', 'Site visits', 'cal', None), ('inv', 'Inventory', 'box', None), ('camp', 'Campaigns', 'phone', None), ('-', 'Reports', '', None), ('reports', 'Reports', 'chart', None)],
  activity=[('14:33', '<b>Priya Mehta</b> · called in 31 s · hot · visit Sun 3:00'), ('14:20', '<b>Anil Gupta</b> · price question → Vikram'), ('13:10', '<b>Unit B-704</b> · token received · blocked for 7 days'), ('12:00', '<b>Portal lead</b> · 99acres · duplicate of WhatsApp lead · merged'), ('06:00', '<b>Digest</b> · 6 visits today · 3 tokens due')])
SCREENS = [
 dict(slug='today', nav='home', title='Today', crumb='Tue 16 Sep · Vesu Heights + Pal Gardens',
  caption='Every enquiry from four portals, ads and walk-ins in one place — called within 30 seconds, followed up by the system, and shown to the sales head as a short list.',
  body=kpis([('38', 'enquiries today', ('4 portals + ads', '')), ('31 s', 'median first call', ('was 4 h', 'up')), ('6', 'site visits today', ('2 with spouse', ''), 'r'), ('₹4.6 Cr', 'at token stage', ('3 tokens due this week', 'up'))]) + '<div class="grid g2">' + card('Needs you', lst([('14:20', '<b>Anil Gupta</b> · 2nd discount request · AI handed over · you joined at 1:05', tag('on call', 'r')), ('13:10', '<b>Unit B-704</b> · token ₹2 L · agreement draft by Thu?', tag('decide', 'w')), ('11:40', '<b>Deepa Nair</b> · 3rd callback · ladder suggests a call from you', tag('call', '')), ('09:12', '<b>"Vesu Sept" ad</b> · cost / qualified ₹1,140 · below target', tag('ok', 'g'))]), '4') + card('Where enquiries came from · today', hbars([('WhatsApp / Instagram ad', 100, '16', ''), ('99acres', 44, '7', ''), ('MagicBricks', 38, '6', ''), ('Website', 31, '5', ''), ('Walk-in / referral', 25, '4', 'g')]) + '<div class="mono">3 duplicates merged across portals</div>') + '</div>'),
 dict(slug='lead', nav='leads', title='Lead · Priya Mehta', crumb='Leads › Vesu Heights › Priya Mehta', topbtn='<button class="btn ghost">WhatsApp</button>&nbsp;<button class="btn">Book visit</button>',
  caption='One lead, every touch: the AI call transcript, the WhatsApp thread, the visit, the units shown, the loan status — and what happens next without anyone remembering.',
  body='<div class="grid g3">' + card('Profile', kv([('Phone', '+91 98••• 4471'), ('Source', 'Website · 14:28 · called 14:28:31'), ('Need', '2 BHK · Vesu · park view'), ('Budget', '~₹80 L (from call)'), ('Loan', 'Salaried · HDFC pre-approval started'), ('Family', 'Spouse joining Sunday'), ('Owner', 'Kiran (site) · Vikram (desk)')]), tag('hot', 'r')) + card('Journey', timeline([('Website enquiry', '14:28', 'on'), ('AI call · 2:14 · booked visit', '14:31', 'on'), ('WhatsApp: location + brochure', '14:32', 'on'), ('Loan desk call', 'Wed 11:00 · Rahul', 'cur'), ('Site visit · Kiran', 'Sun 15:00', ''), ('Token ladder', '3 nudges over 6 days', '')])) + card('Units shortlisted', table(['Unit', 'Type', 'Price', 'Status'], [['B-704', '2 BHK · park', '₹79.5 L', tag('token · other buyer', 'w')], ['B-604', '2 BHK · park', '₹78.8 L', tag('available', 'g')], ['C-1102', '2 BHK · road', '₹76.2 L', tag('available', 'g')]]) + '<div class="mono">B-704 blocked 7 d · show B-604 first</div>') + '</div>' + card('AI call · 14:31 · 2:14', '<div class="list"><div><span class="t" style="width:60px;color:var(--red)">AGENT</span><div>Namaste Priya ji, Shubham Developers se Anjali. Aapne abhi Vesu ke liye enquiry ki — do minute?</div></div><div><span class="t" style="width:60px">PRIYA</span><div>Haan. 2 BHK chahiye, budget around 80 lakh.</div></div><div><span class="t" style="width:60px;color:var(--red)">AGENT</span><div>Vesu mein 2 BHK 76 se 84 lakh, possession March 2027. Sunday site visit chalega? Kiran milenge.</div></div><div><span class="t" style="width:60px">PRIYA</span><div>Sunday 3 baje theek hai.</div></div></div>', 'transcript · sentiment +0.62')),
 dict(slug='pipeline', nav='board', title='Pipeline', crumb='Vesu Heights · 84 open · ₹4.6 Cr at token', topbtn='<div class="chips"><span class="chip on">Vesu Heights</span><span class="chip">Pal Gardens</span><span class="chip">All</span></div>',
  caption='Stages move from events — a call outcome, a visit logged on the phone, a token received — so the board is true without anyone updating it.',
  body=kanban([('New · called', [('Rahul Mehta', '3 BHK · 1.1 Cr · called 10:21', 'price → Vikram', ('handover', 'r'), 'hot'), ('Kavita Rao', '2 BHK · Pal', 'callback 18:00', ('AI', ''), ''), ('Jignesh P', 'Shop 400 sq ft', 'AI replied', ('AI', ''), ''), ('Mansi T', '2 BHK · Vesu', 'no answer 2/3', ('retry', 'w'), '')]), ('Qualified', [('Priya Mehta', '2 BHK · ~80 L', 'visit Sun 15:00', ('visit booked', 'b'), 'hot'), ('Kiran Patel', '3 BHK · loan ✓', 'visit Sat', ('loan ✓', 'g'), ''), ('Deepa Nair', '2 BHK · callback ×3', 'rung 3', ('call from you', 'w'), '')]), ('Visited', [('Farah Sheikh', 'Sat · with spouse', 'token due Fri', ('₹2 L', 'b'), ''), ('Suresh Iyer', '3 BHK · higher floor', 'nudge 2 of 3', ('AI', ''), ''), ('Nikhil Shah', 'B-704 shown', 'token 13:10', ('→ Token', 'g'), '')]), ('Token', [('Nikhil Shah', 'B-704 · ₹2 L · 13:10', 'agreement Thu', ('blocked 7 d', 'g'), ''), ('Rina D', 'C-1102 · cheque', '15 Sep', ('clearing', ''), '')]), ('Agreement', [('Amit K', 'A-1204 · ₹84 L', 'registry 22 Sep', ('booked', 'g'), '')])])),
 dict(slug='visits', nav='visits', title='Site visits', crumb='This week · 31 booked · 6 today', topbtn='<button class="btn ghost">Print schedule</button>',
  caption='Visits booked by the AI on the call, reminded on WhatsApp, logged on the site team\'s phone — and a no-show gets a re-booking call, not a cold lead.',
  body='<div class="grid" style="grid-template-columns: 1.3fr 1fr">' + table(['When', 'Lead', 'Need', 'Site person', 'Reminder', 'Outcome'], [['Today 11:00', '<b>Sneha Desai</b>', '2 BHK · with spouse', 'Kiran', tag('sent · confirmed', 'g'), tag('interested · other floor', 'b')], ['Today 13:00', '<b>Kiran Patel</b>', '3 BHK · corner', 'Kiran', tag('sent · confirmed', 'g'), tag('in progress', '')], ['Today 16:30', '<b>Farah Sheikh</b>', '2nd visit · parents', 'Kiran', tag('sent', 'g'), tag('upcoming', '')], ['Sun 15:00', '<b>Priya Mehta</b>', '2 BHK · park view', 'Kiran', tag('Sat 20:00', ''), tag('booked by AI call', 'b')], ['Sat 11:00', '<b>Deepa S</b>', '2 BHK · with spouse', 'Rahul', tag('Fri 20:00', ''), tag('booked by AI call', 'b')], ['Yesterday 11:00', '<b>Mohan L</b>', '2 BHK', 'Kiran', tag('sent', 'g'), tag('no-show → AI call → rebooked Wed', 'w')]]) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('No-shows · 30 days', hbars([('Booked', 100, '118', ''), ('Showed', 82, '97', 'g'), ('No-show', 18, '21', 'r'), ('Re-booked by AI call', 14, '16', 'g')]) + '<div class="mono">No-show rate 27% → 18% after the call rung</div>') + card('Site team · phone', lst([('11:40', 'Kiran tapped "Interested · other floor" · Sneha Desai'), ('11:41', 'Ladder: floor plan of 6th floor sent 17:40'), ('11:41', 'Vikram notified in Today')]), 'one tap') + '</div></div>'),
 dict(slug='inventory', nav='inv', title='Inventory · Vesu Heights', crumb='Tower B · 96 units · 61 sold · 4 blocked', topbtn='<div class="chips"><span class="chip on">Tower B</span><span class="chip">Tower A</span><span class="chip">Tower C</span></div>',
  caption='Unit inventory with live status — available, blocked on token, sold — so two salespeople never promise the same flat, and the AI never quotes a unit that is gone.',
  body='<div class="grid" style="grid-template-columns: 1.4fr 1fr">' + card('Tower B · floors 12 → 1', '<div class="grid" style="grid-template-columns: repeat(8, 1fr); gap: 6px">' + ''.join(f'<div class="card" style="padding:8px;gap:2px;border-radius:8px;{st}"><b style="font-size:11.5px">{u}</b><span style="font-size:10px;color:var(--muted)">{t}</span></div>' for u, t, st in [(f'B-{fl}0{n}', ['2 BHK', '2 BHK', '3 BHK', '3 BHK'][n - 1], ('background:var(--bg2);color:var(--muted)' if (fl * 4 + n) % 3 else ('border-color:var(--warn);background:var(--warn-soft)' if (fl, n) in [(7, 4), (6, 2), (9, 1), (11, 3)] else 'border-color:var(--ok)'))) for fl in range(12, 4, -1) for n in range(1, 5)]) + '</div><div class="row" style="gap:14px;margin-top:8px"><span class="pill"><span class="dot" style="background:var(--line2)"></span>Sold</span><span class="pill"><span class="dot g"></span>Available</span><span class="pill"><span class="dot w"></span>Blocked · token</span></div>') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('B-704', kv([('Type', '2 BHK · 1,140 sq ft · park view'), ('Price', '₹79.5 L · all-in'), ('Status', 'Blocked · token ₹2 L · Nikhil Shah'), ('Blocked till', 'Tue 23 Sep · auto-release'), ('Shortlisted by', '3 other leads → shown B-604')]), tag('blocked', 'w')) + card('Availability · Tower B', hbars([('Sold', 64, '61', ''), ('Available', 32, '31', 'g'), ('Blocked', 4, '4', 'w')])) + '</div></div>'),
 dict(slug='campaigns', nav='camp', title='Campaigns', crumb='AI calls + WhatsApp · this month', fill=True,
  caption='The calling agent and WhatsApp ladders run as campaigns you can see: enquiry follow-up, visit reminders, token nudges, old-lead revival.',
  body=table(['Campaign', 'Trigger', 'Channel', 'Progress', 'Result', 'Status'], [['<b>Enquiry follow-up</b>', 'New lead → call in 30 s', 'AI call + WhatsApp', '640 / 900', '71 hot · 52 visits', tag('running', 'g')], ['<b>Visit reminders</b>', 'Visit −1 day 20:00', 'WhatsApp', '118 / 118', '97 showed', tag('running', 'g')], ['<b>No-show re-book</b>', 'No-show logged', 'AI call', '21 / 21', '16 re-booked', tag('running', 'g')], ['<b>Token nudges</b>', 'Visit +3 / +6 / +9 d', 'WhatsApp → human', '86 / 118', '28 tokens', tag('running', 'g')], ['<b>Old-lead revival · Pal Gardens</b>', 'Leads quiet > 60 d · price drop', 'AI call', '0 / 412', '—', tag('scheduled Sat', 'b')]])),
 dict(slug='reports', nav='reports', title='Reports', crumb='Sep 2026', fill=True, topbtn='<div class="chips"><span class="chip">Week</span><span class="chip on">Month</span></div>',
  caption='Source to token by portal, ad and person; response times; where leads leak — the report the owner used to ask for on Monday, ready every morning.',
  body=kpis([('412', 'enquiries', ('+18%', 'up')), ('99%', 'called within 60 s', ('was 68% same day', 'up')), ('118', 'site visits', None), ('28', 'tokens · ₹5.6 Cr', ('+9 vs Aug', 'up'), 'r')]) + '<div class="grid g2">' + card('By source', table(['Source', 'Enq.', 'Visits', 'Tokens', 'Cost / token'], [['Instagram · Vesu Sept', '#164', '#52', '#14', '#₹8,900'], ['99acres', '#84', '#22', '#5', '#₹19,400'], ['MagicBricks', '#62', '#15', '#3', '#₹24,100'], ['Website', '#58', '#18', '#4', '#₹6,200'], ['Walk-in / referral', '#44', '#11', '#2', '#—']])) + card('Where leads leak', hbars([('No answer ×3', 31, '31%', 'w'), ('Budget mismatch', 22, '22%', ''), ('Visit no-show', 18, '18%', 'r'), ('Booked elsewhere', 14, '14%', ''), ('Loan', 9, '9%', '')])) + '</div>'),
]
