# WhatsApp CRM — screens for Shubham Developers (Surat) sales desk. Fictional.
APP = dict(brand='LeadDesk', sub='WhatsApp CRM', client='Shubham Developers', user='Vikram Shah', role='Sales head',
  nav=[('home', 'Today', 'home', None), ('inbox', 'Team inbox', 'inbox', 14), ('leads', 'Leads', 'users', None), ('board', 'Pipeline', 'board', None), ('ladder', 'Follow-up ladders', 'ladder', None), ('-', 'Reports', '', None), ('reports', 'Reports', 'chart', None), ('settings', 'Settings', 'cog', None)],
  activity=[('10:34', '<b>Sneha Desai</b> · visit booked Sun 11:00 · Kiran assigned · reminder Sat 20:00'), ('10:21', '<b>Rahul Mehta</b> · 2nd price question → handover to Vikram'), ('09:58', '<b>Farah Sheikh</b> · visit confirmed · token reminder Thu'), ('09:12', '<b>3 new enquiries</b> from “Vesu Sept” · replied in 29 s, 31 s, 44 s'), ('06:00', '<b>Owner digest</b> sent · 6 visits today · ₹4.6 Cr at token stage')])

def conv(n, pv, t, on=False, b=None, av=None):
    return f'<div class="ci{" on" if on else ""}"><div class="avatar{" g" if b else ""}">{av or n[:1]}</div><div><div class="nm">{n}</div><div class="pv">{pv}</div></div><div style="text-align:right"><div class="t">{t}</div>{f"<span class=\"b\">{b}</span>" if b else ""}</div></div>'
CONVS = ''.join([conv('Sneha Desai', 'Sunday works. Send brochure please.', '10:34', on=True, b=1), conv('Rahul Mehta', 'Rate kya hai 3 BHK ka?', '10:21', b=2), conv('Farah Sheikh', 'Visit booked · Sat 11:00 ✓', '09:58'), conv('Kiran Patel', 'Loan pre-approval attached', '09:40'), conv('Deepa Nair', 'Call me tomorrow after 6', 'Yesterday'), conv('Anil Gupta', 'Handover → Vikram', 'Yesterday'), conv('Mohan L', 'Not interested — booked elsewhere', 'Mon'), conv('Priya Mehta', '📍 Location shared', 'Mon')])
CHAT = '''<div class="wa"><div class="hd"><div class="avatar g" style="width:32px;height:32px;font-size:11px">SD</div><div>Sneha Desai<small>+91 98••• 4471 · via Instagram ad · Vesu 2 BHK</small></div><span class="tag g" style="margin-left:auto">warm</span></div><div class="msgs">
<div class="bub">Hi, saw your ad. 2 BHK in Vesu available? Budget 75–80 lakh.<div class="m">10:02</div></div>
<div class="bub me">Hi Sneha, yes — 2 BHK at Vesu Heights from ₹76 L, possession March 2027. Would you like a site visit this weekend? Kiran from our team will meet you.<div class="m">10:03 · sent by AI · reviewed</div></div>
<div class="bub">Sunday works. Send brochure please.<div class="m">10:34</div></div>
<div class="bub me">Brochure and price sheet attached. Visit booked for Sun 21 Sep, 11:00 — map link below. Kiran: +91 97••• 1180.<div class="m">10:34 · sent by AI</div></div>
<div class="bub sys">Lead card updated: budget ₹75–80 L · visit Sun 21 Sep 11:00 · Kiran assigned · reminder Sat 20:00</div>
</div><div class="in"><div class="f">Reply as Vikram… (⌘K for a template)</div><button class="btn sm">Send</button></div></div>'''
SIDE = '''<div class="side"><div class="sec"><div class="row between"><b>Lead card</b><span class="mono">written from the chat</span></div><div class="kv"><span class="k">Name</span><span>Sneha Desai</span><span class="k">Source</span><span>Instagram ad · Vesu</span><span class="k">Need</span><span>2 BHK · Vesu</span><span class="k">Budget</span><span>₹75–80 L</span><span class="k">Stage</span><span><span class="tag b">Visit booked</span></span><span class="k">Owner</span><span>Kiran (site) · Vikram</span></div></div>
<div class="sec"><b>Next steps</b><div class="list"><div><span class="t">Sat 20:00</span>Visit reminder on WhatsApp</div><div><span class="t">Sun 11:00</span>Site visit · Kiran</div><div><span class="t">Sun 18:00</span>If no-show → call from AI agent</div></div></div>
<div class="sec"><b>Ladder</b><span class="tag">Visit booked · rung 2 of 5</span><div class="bar"><i style="width:40%"></i></div></div></div>'''

SCREENS = [
 dict(slug='inbox', nav='inbox', title='Team inbox', crumb='14 open · 3 waiting on us', topbtn='<button class="btn red">New lead</button>',
   caption='Every WhatsApp conversation in one team inbox. The AI drafts the reply, the lead card on the right is written from the chat — nobody types it.',
   body=f'<div class="inbox"><div class="conv"><div class="srch">🔍 Search chats</div>{CONVS}</div>{CHAT}{SIDE}</div>'),
 dict(slug='today', nav='home', title='Today', crumb='Tue 16 Sep · compiled 06:00', 
   caption='The morning view: what needs a person today, what the system already did overnight, and where the pipeline stands.',
   body='''<div class="grid g4"><div class="card kpi"><div class="v">38</div><div class="s">new enquiries this week</div><div class="d up">+12 vs last week</div></div><div class="card kpi"><div class="v">31 s</div><div class="s">median first response</div><div class="d up">target 60 s</div></div><div class="card kpi r"><div class="v">6</div><div class="s">visits booked today</div><div class="d">2 with spouse</div></div><div class="card kpi"><div class="v">₹4.6 Cr</div><div class="s">token-stage pipeline</div><div class="d up">3 tokens due this week</div></div></div>
<div class="grid g2"><div class="card"><div class="h">Needs you <span class="mono">4</span></div><div class="list"><div><span class="dot r"></span><div><b>Rahul Mehta</b> asked for a discount twice — price question, handover rule<span class="sub" style="display:block;color:var(--muted);font-size:11px">Draft ready · 10:21</span></div><button class="btn sm ghost" style="margin-left:auto">Open</button></div><div><span class="dot w"></span><div><b>Deepa Nair</b> — 3rd callback request; ladder suggests a call from you</div><button class="btn sm ghost" style="margin-left:auto">Call</button></div><div><span class="dot b"></span><div><b>Token due</b> · Farah Sheikh · ₹2 L by Fri — reminder scheduled Thu 10:00</div><button class="btn sm ghost" style="margin-left:auto">View</button></div><div><span class="dot"></span><div><b>Ad campaign</b> "Vesu Sept" — 22 leads, 9 qualified, cost/qualified ₹1,140</div><button class="btn sm ghost" style="margin-left:auto">Report</button></div></div></div>
<div class="card"><div class="h">Done overnight by the system <span class="mono">since 20:00</span></div><div class="list"><div><span class="t">20:00</span>11 visit reminders sent · 9 confirmed</div><div><span class="t">21:15</span>3 first replies to new enquiries (31 s, 28 s, 44 s)</div><div><span class="t">22:40</span>Lead cards written for 3 new leads · budgets captured</div><div><span class="t">06:00</span>Ladder moved 7 leads · 2 escalated to you</div><div><span class="t">06:00</span>Owner digest sent to Mr. Shah</div></div></div></div>'''),
 dict(slug='lead', fill=True, nav='leads', title='Lead · Sneha Desai', crumb='Leads › Vesu Heights › Sneha Desai', topbtn='<button class="btn ghost">Edit</button>&nbsp;<button class="btn">Book visit</button>',
   caption='A lead card written by the AI from the conversation — need, budget, source, next step — with the full history and every promise the ladder is holding.',
   body='''<div class="grid" style="grid-template-columns: 1.1fr 1fr 1fr"><div class="card"><div class="h">Profile <span class="tag g">warm</span></div><div class="kv"><span class="k">Phone</span><span>+91 98••• 4471</span><span class="k">Source</span><span>Instagram ad · "Vesu Sept"</span><span class="k">Project</span><span>Vesu Heights · 2 BHK</span><span class="k">Budget</span><span>₹75–80 L <span class="mono">read from chat</span></span><span class="k">Loan</span><span>Pre-approval pending · HDFC</span><span class="k">Family</span><span>Spouse joining visit</span><span class="k">Owner</span><span>Kiran (site) · Vikram (desk)</span><span class="k">Created</span><span>16 Sep 10:02 · reply in 31 s</span></div></div>
<div class="card"><div class="h">Journey</div><div class="timeline"><div><span class="n on">✓</span><div>Enquiry from ad<small>16 Sep 10:02</small></div></div><div><span class="n on">✓</span><div>First reply by AI · reviewed by Vikram<small>10:03 · 31 s</small></div></div><div><span class="n on">✓</span><div>Budget + need captured<small>10:02</small></div></div><div><span class="n on">✓</span><div>Brochure sent · visit booked<small>10:34</small></div></div><div><span class="n cur">5</span><div>Site visit · Kiran<small>Sun 21 Sep 11:00</small></div></div><div><span class="n">6</span><div>Token<small>ladder: 3 nudges over 6 days</small></div></div></div></div>
<div class="card"><div class="h">Promises being held</div><div class="list"><div><span class="t">Sat 20:00</span>Visit reminder (WhatsApp)</div><div><span class="t">Sun 18:00</span>No-show → call from AI agent</div><div><span class="t">Mon 10:00</span>Post-visit: price sheet + loan help</div><div><span class="t">+3 d</span>Nudge 1 · "any questions after the visit?"</div></div><div class="card flat" style="gap:4px"><span class="mono">Suggested next</span><b>Send the floor-plan video before Sunday — 2 BHK buyers who see it convert 1.6× on visit.</b><button class="btn sm" style="align-self:flex-start">Send now</button></div></div></div>
<div class="card"><div class="h">Conversation <span class="mono">4 messages · 2 by AI</span></div><div class="list"><div><span class="t">10:02</span><b>Sneha</b>&nbsp;Hi, saw your ad. 2 BHK in Vesu available? Budget 75–80 lakh.</div><div><span class="t">10:03</span><b>AI</b>&nbsp;Hi Sneha, yes — 2 BHK at Vesu Heights from ₹76 L, possession March 2027…</div><div><span class="t">10:34</span><b>Sneha</b>&nbsp;Sunday works. Send brochure please.</div><div><span class="t">10:34</span><b>AI</b>&nbsp;Brochure and price sheet attached. Visit booked for Sun 21 Sep, 11:00…</div></div></div>'''),
 dict(slug='pipeline', nav='board', title='Pipeline', crumb='Vesu Heights · 84 open leads · ₹4.6 Cr at token stage', topbtn='<div class="chips"><span class="chip on">All projects</span><span class="chip">Vesu Heights</span><span class="chip">Pal Gardens</span></div>',
   caption='Leads move on their own as the chat progresses — a booked visit, a shared loan letter, a token — no drag-and-drop by anyone.',
   body='''<div class="kan"><div class="col"><div class="ch">New <span>22</span></div><div class="lead hot"><div class="nm">Rahul Mehta</div>3 BHK · budget ₹1.1 Cr<div class="foot"><span class="m">10:21 · price q</span><span class="tag r">handover</span></div></div><div class="lead"><div class="nm">Kavita Rao</div>2 BHK · Pal<div class="foot"><span class="m">09:12</span><span class="tag">AI replied</span></div></div><div class="lead"><div class="nm">Jignesh P</div>Shop · 400 sq ft<div class="foot"><span class="m">08:50</span><span class="tag">AI replied</span></div></div><div class="lead"><div class="nm">Mansi T</div>2 BHK · Vesu<div class="foot"><span class="m">Yesterday</span><span class="tag w">no reply 18 h</span></div></div></div>
<div class="col"><div class="ch">Qualified <span>31</span></div><div class="lead"><div class="nm">Sneha Desai</div>2 BHK · ₹75–80 L<div class="foot"><span class="m">visit Sun</span><span class="tag b">visit booked</span></div></div><div class="lead"><div class="nm">Kiran Patel</div>3 BHK · loan pre-approved<div class="foot"><span class="m">09:40</span><span class="tag g">loan ✓</span></div></div><div class="lead"><div class="nm">Deepa Nair</div>2 BHK · callback ×3<div class="foot"><span class="m">ladder rung 3</span><span class="tag w">call from you</span></div></div></div>
<div class="col"><div class="ch">Visited <span>18</span></div><div class="lead"><div class="nm">Farah Sheikh</div>Visited Sat · with spouse<div class="foot"><span class="m">token due Fri</span><span class="tag b">₹2 L</span></div></div><div class="lead"><div class="nm">Suresh Iyer</div>3 BHK · higher floor<div class="foot"><span class="m">nudge 2 of 3</span><span class="tag">AI nudging</span></div></div><div class="lead"><div class="nm">Priya Mehta</div>2 BHK · visited Sun<div class="foot"><span class="m">price sheet sent</span><span class="tag">waiting</span></div></div></div>
<div class="col"><div class="ch">Token <span>9</span></div><div class="lead"><div class="nm">Nikhil Shah</div>₹2 L received · 14 Sep<div class="foot"><span class="m">agreement Thu</span><span class="tag g">token ✓</span></div></div><div class="lead"><div class="nm">Rina D</div>₹2 L · cheque clearing<div class="foot"><span class="m">15 Sep</span><span class="tag g">token ✓</span></div></div></div>
<div class="col"><div class="ch">Closed / lost <span>4</span></div><div class="lead" style="opacity:.7"><div class="nm">Mohan L</div>Booked elsewhere<div class="foot"><span class="m">Mon</span><span class="tag">lost · no calls 90 d</span></div></div><div class="lead" style="opacity:.7"><div class="nm">Ashok B</div>Budget mismatch<div class="foot"><span class="m">Sun</span><span class="tag">lost</span></div></div></div></div>'''),
 dict(slug='ladder', fill=True, nav='ladder', title='Follow-up ladder · Visit booked', crumb='Ladders › Vesu Heights › Visit booked → Token', topbtn='<button class="btn ghost">Test on a lead</button>&nbsp;<button class="btn">Save</button>',
   caption='The ladder is the product: who is nudged, how, and when it stops being polite — set in plain language, in your team\'s voice, per stage.',
   body='''<div class="grid" style="grid-template-columns: 1.3fr 1fr"><div class="card"><div class="h">Rungs <span class="mono">runs after every visit</span></div><div class="ladder">
<div class="rung"><span class="w">Visit −1 d</span><span class="dt"></span><div>WhatsApp reminder with map, parking, and who will meet them<small style="display:block;color:var(--muted)">"Hi {name}, Kiran will meet you at Vesu Heights tomorrow 11:00…"</small></div><span class="tag g">on</span></div>
<div class="rung"><span class="w">Visit +6 h</span><span class="dt"></span><div>Thank-you + floor plan video + price sheet</div><span class="tag g">on</span></div>
<div class="rung"><span class="w">No-show</span><span class="dt k"></span><div>Call from the AI agent to re-book; if answered, new visit in this ladder</div><span class="tag g">on</span></div>
<div class="rung"><span class="w">+3 d</span><span class="dt"></span><div>Nudge 1 — "any questions after the visit?" (reads reply for objection)</div><span class="tag g">on</span></div>
<div class="rung"><span class="w">+6 d</span><span class="dt"></span><div>Nudge 2 — loan help offer, EMI example for their budget</div><span class="tag g">on</span></div>
<div class="rung"><span class="w">+9 d</span><span class="dt r"></span><div>Escalate to Vikram with the whole thread summarised</div><span class="tag r">human</span></div>
<div class="rung"><span class="w">+14 d</span><span class="dt o"></span><div>Park lead · re-open on any new message or price change</div><span class="tag">stop</span></div></div></div>
<div class="form"><div class="card"><div class="h">Voice & rules</div><div class="fld"><label>Tone</label><div class="in sel">Warm, short, Hinglish OK</div></div><div class="fld"><label>Sends between</label><div class="in">09:00 – 20:00 · Mon–Sun</div></div><div class="sw"><span class="tg"></span>Hand over on any price/discount question</div><div class="sw"><span class="tg"></span>Hand over on frustration (sentiment &lt; −0.4)</div><div class="sw"><span class="tg off"></span>Allow a second message if no reply in 24 h</div></div>
<div class="card flat"><div class="h">Last 30 days on this ladder</div><div class="hbar"><span>Visited</span><div class="bar"><i style="width:100%"></i></div><b>118</b></div><div class="hbar"><span>Replied to nudge</span><div class="bar"><i style="width:61%"></i></div><b>72</b></div><div class="hbar"><span>Token</span><div class="bar"><i class="r" style="width:24%"></i></div><b>28</b></div><div class="hbar"><span>Escalated</span><div class="bar"><i class="w" style="width:12%"></i></div><b>14</b></div></div></div></div>'''),
 dict(slug='reports', nav='reports', title='Reports', crumb='Sep 2026 · all projects', topbtn='<div class="chips"><span class="chip">Week</span><span class="chip on">Month</span><span class="chip">Quarter</span></div>',
   caption='Reports compile themselves: source to token, response times, and where leads leak — by project, by person, by ad.',
   body='''<div class="grid g4"><div class="card kpi"><div class="v">412</div><div class="s">enquiries</div><div class="d up">+18% MoM</div></div><div class="card kpi"><div class="v">38%</div><div class="s">qualified</div><div class="d up">+6 pts</div></div><div class="card kpi"><div class="v">118</div><div class="s">site visits</div><div class="d up">+22</div></div><div class="card kpi r"><div class="v">28</div><div class="s">tokens · ₹5.6 Cr</div><div class="d up">+9 vs Aug</div></div></div>
<div class="grid" style="grid-template-columns: 1.4fr 1fr"><div class="card"><div class="h">Enquiries → tokens, by week</div><div class="bars"><i style="height:60%" class="g"></i><i style="height:22%"></i><i style="height:8%" class="r"></i><i style="height:72%" class="g"></i><i style="height:30%"></i><i style="height:10%" class="r"></i><i style="height:88%" class="g"></i><i style="height:34%"></i><i style="height:12%" class="r"></i><i style="height:100%" class="g"></i><i style="height:40%"></i><i style="height:14%" class="r"></i></div><div class="row" style="gap:16px"><span class="pill"><span class="dot" style="background:var(--line2)"></span>Enquiries</span><span class="pill"><span class="dot" style="background:var(--ink)"></span>Visits</span><span class="pill"><span class="dot r"></span>Tokens</span></div></div>
<div class="card"><div class="h">Where leads leak</div><div class="hbar"><span>No reply to 1st msg</span><div class="bar"><i class="w" style="width:31%"></i></div><b>31%</b></div><div class="hbar"><span>Budget mismatch</span><div class="bar"><i style="width:22%"></i></div><b>22%</b></div><div class="hbar"><span>Visit no-show</span><div class="bar"><i class="r" style="width:18%"></i></div><b>18%</b></div><div class="hbar"><span>Booked elsewhere</span><div class="bar"><i style="width:14%"></i></div><b>14%</b></div><div class="hbar"><span>Loan</span><div class="bar"><i style="width:9%"></i></div><b>9%</b></div><div class="card flat" style="gap:2px"><span class="mono">AI note</span>No-shows fell from 27% to 18% after the AI call rung was added on 2 Sep.</div></div></div>
<table><tr><th>Source</th><th>Enquiries</th><th>Qualified</th><th>Visits</th><th>Tokens</th><th>Cost / token</th><th>Median 1st reply</th></tr><tr><td>Instagram · "Vesu Sept"</td><td class="num">164</td><td class="num">71</td><td class="num">52</td><td class="num">14</td><td class="num">₹8,900</td><td class="num">29 s</td></tr><tr><td>Google · brand</td><td class="num">98</td><td class="num">44</td><td class="num">31</td><td class="num">8</td><td class="num">₹6,200</td><td class="num">33 s</td></tr><tr><td>Walk-in / referral</td><td class="num">86</td><td class="num">31</td><td class="num">26</td><td class="num">5</td><td class="num">—</td><td class="num">41 s</td></tr><tr><td>Property portal</td><td class="num">64</td><td class="num">11</td><td class="num">9</td><td class="num">1</td><td class="num">₹31,000</td><td class="num">28 s</td></tr></table>'''),
 dict(slug='mobile', fill=True, nav='inbox', title='On the phone', crumb='Kiran · site team · Sunday 10:52',
   caption='The site team works from their phone: today\'s visits, the lead card before the buyer arrives, and one tap to log the outcome.',
   body='''<div class="row top" style="gap:32px;align-items:flex-start"><div class="phone"><div class="ph"><b>Today · Sun 21 Sep</b><small>3 visits · Vesu Heights</small></div><div class="pb"><div class="card" style="padding:12px 14px;gap:6px;border-color:var(--red)"><div class="row between"><b>11:00 · Sneha Desai</b><span class="tag b">in 8 min</span></div><div style="font-size:12px;color:var(--ink2)">2 BHK · ₹75–80 L · spouse joining · loan pending</div><div style="font-size:12px"><b>Show:</b> 2 BHK type-B, 7th floor · park view</div><div class="row" style="gap:6px;margin-top:4px"><button class="btn sm">Call</button><button class="btn sm ghost">Open card</button></div></div><div class="card" style="padding:12px 14px;gap:6px"><div class="row between"><b>13:00 · Kiran Patel</b><span class="tag">3 BHK</span></div><div style="font-size:12px;color:var(--ink2)">Loan pre-approved · wants corner unit</div></div><div class="card" style="padding:12px 14px;gap:6px"><div class="row between"><b>16:30 · Farah Sheikh</b><span class="tag g">2nd visit</span></div><div style="font-size:12px;color:var(--ink2)">Bringing parents · token discussion</div></div><div class="card flat" style="padding:12px 14px;gap:8px"><span class="mono">After the visit</span><div class="row" style="gap:6px;flex-wrap:wrap"><span class="chip">Interested</span><span class="chip">Wants other floor</span><span class="chip">Price issue</span><span class="chip">No-show</span></div><div style="font-size:11.5px;color:var(--muted)">One tap → the desk and the ladder update themselves.</div></div></div></div>
<div class="card" style="max-width:560px"><div class="h">What one tap does</div><div class="timeline"><div><span class="n on">1</span><div>Kiran taps <b>Interested · wants other floor</b> at 11:40</div></div><div><span class="n on">2</span><div>Lead moves to <b>Visited</b>; note written to the card; Vikram sees it in Today</div></div><div><span class="n on">3</span><div>Ladder starts: thank-you + 6th-floor plan sent at 17:40 (visit +6 h)</div></div><div><span class="n on">4</span><div>Nudge 1 in 3 days unless Sneha replies first — then the AI answers or hands over</div></div><div><span class="n cur">5</span><div>Owner digest on Monday: "Sneha Desai · visited · other floor · nudge scheduled"</div></div></div><div class="card flat" style="gap:2px"><span class="mono">Offline?</span>Outcomes queue on the phone and sync when the signal returns. Nothing is lost at the site.</div></div></div>''')
]
