# WhatsApp chatbot — Gupta Pipes (Lucknow) dealer support. Fictional.
from _lib import *
APP = dict(brand='DealerBot', sub='WhatsApp chatbot', client='Gupta Pipes', user='Vikram Gupta', role='Sales manager',
  nav=[('home', 'Today', 'home', None), ('conv', 'Conversations', 'inbox', 6), ('kb', 'Knowledge', 'doc', None), ('hand', 'Handovers', 'users', 'g3'), ('flows', 'Flows', 'ladder', None), ('-', 'Reports', '', None), ('reports', 'Reports', 'chart', None), ('settings', 'Settings', 'cog', None)],
  activity=[('21:06', '<b>Sharma Traders</b> · price question → Vikram · call by 10:00'), ('19:41', '<b>Agarwal Sanitary</b> · complaint CMP-2291 logged with photos → dispatch'), ('18:14', '<b>New dealer enquiry</b> · Lucknow · brochure sent · lead created'), ('17:02', '<b>Knowledge gap</b> · CPVC price list asked ×4 today'), ('16:40', '<b>112 order-status answers</b> since 09:00 · 0 handovers')])
SCREENS = [
 dict(slug='conversation', fill=True, nav='conv', title='Conversations · Sharma Traders', crumb='Dealer · Kanpur · credit OK', topbtn='<button class="btn ghost">Take over</button>',
  caption='A dealer asks "order kab aayega?" at 9 pm. The bot answers from the live order — dispatch time, LR number, ETA — in Hinglish, and knows when to hand over.',
  body='<div class="grid" style="grid-template-columns: 1fr 1fr; flex:1; min-height:0">' + wa('Sharma Traders · Ramesh', 'Dealer · Kanpur · +91 99••• 1180', [('', 'order kab aayega?', '21:04'), ('me', 'Ramesh ji, aapka order DO-26-1187 (40 × 110mm SWR pipe, 120 × elbows) aaj 14:10 pe dispatch hua — LR 44821, Verma Roadways. Kanpur godown ETA: <b>Thu 18 Sep, by 2 pm</b>.', '21:04 · bot'), ('', 'invoice bhejo', '21:05'), ('me', '📄 Invoice GP/26-27/2291 · ₹1,86,400 · due 18 Oct (30 days). Aapka credit balance: ₹4.2 L of ₹6 L.', '21:05 · bot'), ('', 'rate kam karo 110mm ka', '21:06'), ('me', 'Rate ki baat Vikram ji karenge — main unhe abhi bata raha hoon, subah 10 baje tak call aayega. Aur kuch chahiye?', '21:06 · bot · handover'), ('sys', 'Handover: price question → Vikram · summary attached · dealer marked "asked for rate on 110mm"')], av='ST', warm=('dealer', 'b')) +
  '<div style="display:flex;flex-direction:column;gap:12px;min-height:0;overflow:hidden">' + card('Answered from', kv([('Order', 'DO-26-1187 · dispatched 14:10'), ('Transport', 'LR 44821 · Verma Roadways · ETA Thu'), ('Invoice', 'GP/26-27/2291 · ₹1,86,400 · due 18 Oct'), ('Credit', '₹4.2 L used of ₹6 L limit'), ('Language', 'Hinglish · dealer\'s usual')]), 'live ERP data') + card('Why it handed over', lst([('Rule', '<b>Price or discount</b> → human (always)'), ('To', 'Vikram · summary + last 6 messages'), ('Promise', 'Call by 10:00 · task created'), ('If missed', 'Reminder at 09:45 · escalate 10:30')]), 'rule 2 of 5') + '</div></div>'),
 dict(slug='today', nav='home', title='Today', crumb='Tue 16 Sep · 21:30',
  caption='What the bot handled today, what it handed over, and the questions it couldn\'t answer — each one a gap in the knowledge base you can close in a minute.',
  body=kpis([('184', 'conversations today', ('71% after 6 pm', 'up')), ('88%', 'answered by the bot', ('no human needed', 'up')), ('14', 'handovers', ('9 price · 3 complaint · 2 unknown', ''), 'r'), ('11 s', 'median reply', None)]) + '<div class="grid g2">' + card('Handovers waiting', lst([('21:06', '<b>Sharma Traders</b> · rate on 110mm · call by 10:00 · Vikram', tag('price', 'r')), ('19:40', '<b>Agarwal Sanitary</b> · damaged elbows in DO-1179 · photo attached', tag('complaint', 'w')), ('18:12', '<b>New number</b> · "dealership kaise milegi?" · Lucknow', tag('lead', 'b'))]), '3') + card('Couldn\'t answer · add to knowledge', lst([('×4', '"CPVC 1 inch ka rate list?" — no price list uploaded for CPVC', '<button class="btn sm ghost">Add</button>'), ('×2', '"Saturday delivery hoti hai?" — no rule on Saturday dispatch', '<button class="btn sm ghost">Add</button>'), ('×1', '"ISI certificate bhejo" — file missing', '<button class="btn sm ghost">Add</button>')]), '7 gaps') + '</div>' + card('By question type · today', hbars([('Order status / ETA', 100, '71', ''), ('Invoice / ledger / credit', 58, '41', ''), ('Product & availability', 44, '31', ''), ('Price (handover)', 13, '9', 'r'), ('Complaints (handover)', 4, '3', 'w'), ('New enquiries', 8, '6', 'g')]))),
 dict(slug='knowledge', fill=True, nav='kb', title='Knowledge', crumb='What the bot is allowed to say · 6 sources', topbtn='<button class="btn">Add source</button>',
  caption='The bot answers only from sources you approve — the live ERP, your price list, your policies — and shows which source every answer came from.',
  body=table(['Source', 'Type', 'Used for', 'Last updated', 'Answers today', 'Status'], [['<b>ERP · orders, dispatch, invoices</b>', 'Live connection', 'Order status, ETA, invoices, ledger', 'live', '#112', tag('connected', 'g')], ['<b>Price list · SWR & agri</b>', 'Sheet', 'Rates, MOQ, pack sizes', '12 Sep', '#28', tag('ok', 'g')], ['<b>Price list · CPVC</b>', 'Sheet', '—', '—', '#0', tag('missing', 'r')], ['<b>Dispatch & returns policy</b>', 'Document', 'Delivery days, damage claims', '02 Aug', '#9', tag('ok', 'g')], ['<b>Product catalogue</b>', 'PDF · 42 pages', 'Sizes, ISI marks, applications', '20 Jul', '#31', tag('ok', 'g')], ['<b>Dealer onboarding FAQ</b>', 'Document', 'New dealership enquiries', '20 Jul', '#6', tag('ok', 'g')]], sel=2) + '<div class="grid g2">' + card('Never says', switches([('Prices not in an approved list', True), ('Anything about a competitor', True), ('A delivery date the ERP doesn\'t have', True), ('"Sorry, I don\'t know" without offering a human', True)]), 'guardrails') + card('Test a question', form([('Ask as a dealer', 'CPVC 1 inch ka rate kya hai?'), ('Bot would reply', 'CPVC ki rate list abhi update ho rahi hai — Vikram ji 10 baje tak bhej denge. (No approved source → handover)', 'ta')])) + '</div>'),
 dict(slug='handover', fill=True, nav='hand', title='Handovers', crumb='When the bot stops and a person starts', topbtn='<button class="btn">Save rules</button>',
  caption='Handover is a feature, not a failure: price, complaints, frustration, VIP dealers and anything unknown go to a named person with the thread summarised.',
  body='<div class="grid" style="grid-template-columns: 1.2fr 1fr">' + card('Rules', table(['Trigger', 'To', 'Promise to dealer', 'Today'], [['Price or discount question', 'Vikram', 'Call by next 10:00', '#9'], ['Complaint / damage / shortage', 'Dispatch desk', 'Reply within 2 h (working)', '#3'], ['Sentiment below −0.4 (angry)', 'Vikram', 'Immediate', '#0'], ['Dealer on VIP list (top 20)', 'Vikram', 'Immediate, any topic', '#1'], ['No approved source for the answer', 'Sales desk', 'Answer by next working morning', '#2'], ['Asks for a human', 'Sales desk', 'Immediate', '#1']]), 'ranked') + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Handover · Sharma Traders', kv([('Trigger', 'Price question · 110mm SWR'), ('Summary', 'Regular dealer, order dispatched today, asked for a lower rate on 110mm; credit healthy'), ('Suggested', 'Volume slab: 2% at 500+ pcs/month (policy)'), ('Owner', 'Vikram · call by 10:00')]) + '<div class="row"><button class="btn sm">Call now</button><button class="btn sm ghost">Reply in chat</button></div>', '21:06') + card('If the person is late', timeline([('09:45 reminder to Vikram', 'WhatsApp', 'on'), ('10:00 promise time', 'dealer was told', 'cur'), ('10:30 escalate to owner', 'digest + WhatsApp', '')])) + '</div></div>'),
 dict(slug='flows', fill=True, nav='flows', title='Flows · New dealership enquiry', crumb='Flows › Lead capture', topbtn='<button class="btn ghost">Test</button>&nbsp;<button class="btn">Publish</button>',
  caption='Structured flows for the questions that need a shape — a new dealer enquiry, a complaint with a photo, a reorder — mixed with free conversation where a script would be annoying.',
  body='<div class="grid" style="grid-template-columns: 1.4fr 1fr">' + card('Steps', timeline([('Detect: "dealership", "distributor", "agency" + new number', 'intent', 'on'), ('Ask: city and current business (free text, read by AI)', 'captures city, type', 'on'), ('Ask: monthly volume band (buttons: <50k · 50k–2L · 2L+)', 'qualifies', 'on'), ('Send: dealer brochure + margin sheet for their band', 'from approved sources', 'on'), ('Create lead in CRM · assign by territory · promise a call', 'Lucknow → Vikram · Kanpur → Anil', 'on'), ('If no call logged in 24 h → nudge owner; 48 h → owner digest', 'ladder', 'cur')])) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Live run · 18:12', wa('New number', 'Lucknow · first message', [('', 'dealership kaise milegi?', '18:12'), ('me', 'Namaste! Gupta Pipes ki dealership ke liye 2 chhote sawaal: aapka shehar aur abhi kis business mein hain?', '18:12'), ('', 'Lucknow, hardware shop Aminabad', '18:13'), ('me', 'Monthly approx kitna volume? <b>[<50k] [50k–2L] [2L+]</b>', '18:13'), ('', '50k–2L', '18:13'), ('me', '📄 Brochure + margin sheet bheja. Vikram ji kal 11 baje tak call karenge.', '18:14')], av='?'), '') + '</div></div>'),
 dict(slug='reports', nav='reports', title='Reports', crumb='Sep 2026', topbtn='<div class="chips"><span class="chip">Week</span><span class="chip on">Month</span></div>',
  caption='What the bot saved: after-hours questions answered, calls not made to the sales desk, and the questions that keep coming back.',
  body=kpis([('4,120', 'conversations', ('+31% MoM', 'up')), ('86%', 'answered without a person', ('target 85%', 'up')), ('2,960', 'after-hours answers', ('would have waited till morning', 'up')), ('312', 'handovers', ('62% price', ''))]) + '<div class="grid" style="grid-template-columns: 1.3fr 1fr">' + card('Conversations by hour', bars([(20, 'g'), (18, 'g'), (35, ''), (60, ''), (80, ''), (70, ''), (65, ''), (72, ''), (85, ''), (100, 'r'), (92, 'r'), (74, 'r'), (40, 'g')]) + '<div class="row between mono"><span>09:00</span><span>18:00 → after hours in red</span><span>22:00</span></div>') + card('Top questions · month', hbars([('Order kab aayega', 100, '1,410', ''), ('Invoice / ledger', 62, '870', ''), ('Rate (→ human)', 22, '312', 'r'), ('Stock / availability', 40, '560', ''), ('Damage / shortage', 9, '128', 'w')])) + '</div>'),
 dict(slug='phone', fill=True, nav='conv', title='Dealer side', crumb='Agarwal Sanitary · complaint with photo · 19:40',
  caption='A complaint with a photo: the bot logs it against the delivery, asks the two questions dispatch needs, and hands over with everything attached — no "please call our office".',
  body='<div class="row top" style="gap:32px">' + phone('WhatsApp', 'Gupta Pipes · business', '<div class="bub me" style="max-width:92%">📷 Photo<div class="m">19:40</div></div><div class="bub me" style="max-width:92%">4 elbow tute hue aaye DO-1179 mein<div class="m">19:40</div></div><div class="bub" style="max-width:92%">Sorry Agarwal ji. DO-1179 (dispatched 14 Sep, LR 44790) ke against complaint log kar di: <b>CMP-2291</b>. Do sawaal: kitne cartons damaged the, aur box ki photo hai?<div class="m">19:40 · bot</div></div><div class="bub me" style="max-width:92%">1 carton, box bhi photo bhejta hoon<div class="m">19:41</div></div><div class="bub" style="max-width:92%">Dhanyavaad. Dispatch team subah 10 baje tak replacement ya credit note confirm karegi — aapko yahin update milega.<div class="m">19:41 · bot · handover</div></div><div class="bub sys">CMP-2291 · 4 × elbow 110mm · 1 carton · photos ×2 · → dispatch desk · promise 10:00</div>') + card('Logged against the delivery', kv([('Complaint', 'CMP-2291 · open'), ('Delivery', 'DO-1179 · LR 44790 · Verma Roadways'), ('Items', '4 × elbow 110mm · 1 carton'), ('Evidence', '2 photos · timestamped'), ('Owner', 'Dispatch desk · promise 10:00'), ('Transporter claim', 'Draft ready · ₹1,840')]) + '<div class="row" style="margin-top:6px"><button class="btn sm">Approve credit note</button><button class="btn sm ghost">Send replacement</button></div>', 'CMP-2291', 'style="max-width:560px"') + '</div>'),
]
