# WhatsApp automation for business — Arasu Knits (Tiruppur garment exporter). Fictional.
from _lib import *
APP = dict(brand='FlowDesk', sub='WhatsApp automation', client='Arasu Knits', user='Meena R', role='Merchandiser',
  nav=[('home', 'Today', 'home', None), ('chats', 'Chats', 'inbox', 9), ('orders', 'Orders', 'box', None), ('tasks', 'Tasks', 'check', 'g12'), ('rules', 'Rules & ladders', 'ladder', None), ('-', 'Reports', '', None), ('digest', 'Digests', 'doc', None), ('settings', 'Settings', 'cog', None)],
  activity=[('10:16', '<b>PO 4471</b> · buyer moved delivery to 12 Oct · plan re-scheduled · 2 tasks'), ('09:38', '<b>PO 4468</b> · Ganesh gave 06 Oct on WhatsApp · ladder stopped · decision for Meena'), ('09:00', '<b>11 chases</b> sent for stages due today'), ('08:12', '<b>GRN 1183</b> · fabric received · stage marked · task closed by evidence'), ('06:00', '<b>Digests</b> sent · owner, merchandising, 3 factory heads')])
SCREENS = [
 dict(slug='chat-to-plan', fill=True, nav='chats', title='Chats · Nordic Retail — Lars', crumb='PO 4471 · style 612KX', topbtn='<button class="btn ghost">Open order</button>',
  caption='A buyer changes a date in a WhatsApp thread. The message is read, the plan is re-scheduled, tasks are created, and the chase to the factory is drafted — before anyone opens the ERP.',
  body='<div class="grid" style="grid-template-columns: 1fr 1.1fr; flex:1; min-height:0">' + wa('Nordic Retail — Lars', 'Buyer · PO 4471 · Style 612KX', [('', 'Hi Meena, can you confirm the sampling status on 612KX? Lab dip approved?', '10:12'), ('me', 'Yes Lars, lab dip approved yesterday. Size set goes out Thursday.', '10:15'), ('', 'Good. One change — our warehouse is closed that week. Delivery moved to 12 Oct please.', '10:16'), ('me', 'Noted — 12 Oct. Revised plan shared below. Ex-factory moves to 05 Oct; fabric unchanged.', '10:16 · auto-reply · approved template'), ('sys', 'Read: ETD 05 Oct → 12 Oct · reason: warehouse closed · qty unchanged · plan re-scheduled · 2 tasks created')], av='NR', warm=('buyer', 'b')) +
  '<div style="display:flex;flex-direction:column;gap:12px;min-height:0;overflow:hidden">' + card('What the system read', kv([('Change', 'Delivery 05 Oct → <b>12 Oct</b>'), ('Reason', 'Buyer warehouse closed (from thread)'), ('Quantity', 'Unchanged · 12,000'), ('Confidence', '0.96 · date explicit')]), 'PO 4471') + card('Plan updated', table(['Stage', 'Was', 'Now'], [['Fabric in-house', '08 Sep', '08 Sep <span class="tag">unchanged</span>'], ['Final inspection', '25 Sep', '<b>02 Oct</b>'], ['Ex-factory', '28 Sep', '<b>05 Oct</b>'], ['Handover', '30 Sep', '<b>07 Oct</b>']]), '3 stages moved') + card('Tasks created', lst([('Today', '<b>Confirm revised ex-factory with Koso Tex</b> · Meena'), ('20 Sep', '<b>Re-book final inspection</b> for 02 Oct · Shridhar')]), 'assigned') + '</div></div>'),
 dict(slug='today', nav='home', title='Today', crumb='Tue 16 Sep · compiled 06:00',
  caption='The merchandiser\'s morning: what needs a decision, what the system already chased overnight, and which orders are quiet for too long.',
  body=kpis([('212', 'live orders', ('9 will miss ETD', 'dn')), ('37', 'chases sent since 20:00', ('31 answered', 'up')), ('12', 'tasks for you today', None, 'r'), ('4', 'orders quiet > 48 h', ('ladder escalating', 'dn'))]) + '<div class="grid g2">' + card('Needs you', lst([('PO 4468', '<b>Print 4 days late</b> at Koso Tex · Ganesh gave 06 Oct on the AI call · accept or push?', '<button class="btn sm">Decide</button>'), ('631KX', '<b>Buyer comment on sample rev 2</b> received 22:14 · reply drafted', '<button class="btn sm ghost">Review</button>'), ('GRN', '<b>Fabric rate ₹186 vs PO ₹181.50</b> · query to Deccan drafted', '<button class="btn sm ghost">Review</button>'), ('PO 4459', '<b>Inspection tomorrow 10:00</b> · Uttarasami confirmed · packing list pending', '<button class="btn sm ghost">Open</button>')]), '4') + card('Done overnight', lst([('20:00', '11 stage-due chases on WhatsApp · asked for dates, not status'), ('21:30', '3 replies read → 3 plan dates updated'), ('23:10', 'Ganesh (print) no reply 24 h → second chase, Meena copied'), ('06:00', 'AI call to Ganesh · date captured: 06 Oct'), ('06:00', 'Owner digest sent · 2 orders flagged')]), 'since 20:00') + '</div>'),
 dict(slug='ladder', fill=True, nav='rules', title='Rules & ladders · Stage due', crumb='Ladders › Production stages › Print', topbtn='<button class="btn">Save</button>',
  caption='A chase ladder per stage, in plain language: who is asked, how, when — and when it stops being polite. The wording is your team\'s, not a template.',
  body='<div class="grid" style="grid-template-columns: 1.3fr 1fr">' + card('Rungs', '<div class="ladder"><div class="rung"><span class="w">Due</span><span class="dt"></span><div>Task exists for the unit owner; merchandiser can see it</div>' + tag('on', 'g') + '</div><div class="rung"><span class="w">+4 h</span><span class="dt"></span><div>WhatsApp chase — asks for a <b>date</b>, not a status<small style="display:block;color:var(--muted)">"Ganesh, print end for {style} was due today. Kya date de sakte ho?"</small></div>' + tag('on', 'g') + '</div><div class="rung"><span class="w">+24 h</span><span class="dt"></span><div>Second chase · copies merchandiser · offers two concrete options</div>' + tag('on', 'g') + '</div><div class="rung"><span class="w">+36 h</span><span class="dt k"></span><div>Phone call from the AI agent · revised date captured verbally</div>' + tag('on', 'g') + '</div><div class="rung"><span class="w">+48 h</span><span class="dt r"></span><div>Escalate to unit head with plan impact in days</div>' + tag('human', 'r') + '</div><div class="rung"><span class="w">+72 h</span><span class="dt r"></span><div>One line in the owner\'s morning digest, with the rupee impact</div>' + tag('owner', 'r') + '</div></div>', 'print stage') + '<div class="form">' + card('Behaviour', switches([('Read replies for dates and quantities', True), ('Reset the ladder only when a date is given', True), ('Ask for a photo of the WIP on the second chase', False), ('Never chase between 20:00 and 08:00', True)])) + card('Last 30 days · this ladder', hbars([('Chases sent', 100, '412', ''), ('Date given by rung 2', 64, '264', 'g'), ('Needed the AI call', 21, '86', ''), ('Escalated', 9, '38', 'r')])) + '</div></div>'),
 dict(slug='tasks', nav='tasks', title='Tasks', crumb='Created by the system · 12 for you · 41 for the team', topbtn='<div class="chips"><span class="chip on">Mine</span><span class="chip">Team</span><span class="chip">Overdue</span></div>',
  caption='Nobody writes tasks. They appear from the plan, from messages and from documents — with the reason attached — and close themselves when the evidence arrives.',
  body=table(['Task', 'Order', 'Why it exists', 'Owner', 'Due', 'Status'], [['<b>Confirm revised ex-factory with Koso Tex</b>', 'PO 4471', 'Buyer moved delivery to 12 Oct (WhatsApp, 10:16)', 'Meena', 'Today', tag('new', 'r')], ['<b>Re-book final inspection</b>', 'PO 4471', 'Plan re-scheduled · inspection now 02 Oct', 'Shridhar', '20 Sep', tag('new', 'r')], ['<b>Reply to buyer comment · sample rev 2</b>', '631KX', 'Email from Nordic 22:14 · draft ready', 'Meena', 'Today', tag('draft ready', 'b')], ['<b>Decide: accept 06 Oct print date</b>', 'PO 4468', 'AI call captured date · ETD holds with 1 day slack', 'Meena', 'Today', tag('decision', 'w')], ['<b>Send packing list</b>', 'PO 4459', 'Inspection tomorrow · list missing', 'Priya', 'Today', tag('open', '')], ['<b>Approve fabric invoice</b>', 'GRN 1183', 'Rate ₹186 vs PO ₹181.50', 'Accounts', 'Fri', tag('approval', 'w')], ['<s>Chase lab dip approval</s>', '612KX', 'Approval read from buyer email 15 Sep', 'Meena', '—', tag('closed by evidence', 'g')], ['<s>Confirm fabric in-house</s>', 'PO 4471', 'GRN scanned 08 Sep', 'Stores', '—', tag('closed by evidence', 'g')]], sel=0)),
 dict(slug='orders', fill=True, nav='orders', title='Order · PO 4471', crumb='Orders › Nordic Retail › 612KX · Boys hoodie · 12,000', topbtn='<button class="btn ghost">Message buyer</button>&nbsp;<button class="btn ghost">Message factory</button>',
  caption='Every chase, reply and re-plan is logged against the order — so when a date is missed, the history of who was asked what, and when, is one click away.',
  body='<div class="grid" style="grid-template-columns: 1.4fr 1fr">' + card('Plan · re-scheduled 10:16 from the buyer\'s message', gantt([('Fabric in-house', 2, 14, 'done'), ('Cutting', 16, 10, 'done'), ('Print', 26, 12, 'late'), ('Sewing', 40, 22, ''), ('Finishing', 62, 8, ''), ('Final inspection', 70, 4, ''), ('Ex-factory', 76, 3, '')], ['1 Sep', '8', '15', '22', '29', '6 Oct', '13', '20', '27', '3 Nov'], etd=82), '3 stages moved') + card('Thread · all channels', lst([('10:16', '<b>Buyer</b> · delivery moved to 12 Oct (WhatsApp)'), ('10:16', '<b>System</b> · plan re-scheduled · 2 tasks · reply sent'), ('10:20', '<b>System → Koso Tex</b> · "PO 4471 ex-factory now 05 Oct — confirm by tomorrow"'), ('14:02', '<b>Koso Tex (Ravi)</b> · "Confirmed 05 Oct"'), ('14:02', '<b>System</b> · task closed by reply · Meena notified'), ('15 Sep', '<b>Buyer email</b> · lab dip approved · stage marked')]), 'logged') + '</div>'),
 dict(slug='digest', fill=True, nav='digest', title='Digests', crumb='Owner · 06:00 · Tue 16 Sep', topbtn='<div class="chips"><span class="chip on">Owner</span><span class="chip">Merchandising</span><span class="chip">Factory heads</span></div>',
  caption='One message every morning per role — what moved, what is stuck, what it costs — compiled from the plans and the chats, not typed by anyone.',
  body='<div class="grid" style="grid-template-columns: 1fr 1fr">' + digest('☀ Good morning, Raj · Tue 16 Sep', ['<b>212 live orders</b> · $2.18M · 9 will miss ETD if nothing changes (was 11 yesterday).', '<b>PO 4468 · Koso Tex</b> — print 4 days late; date 06 Oct captured on the AI call; ETD holds with 1 day slack. <i>Meena deciding today.</i>', '<b>PO 4471 · Nordic</b> — buyer moved delivery to 12 Oct; plan re-scheduled; factory confirmed 05 Oct.', '<b>Fabric invoice</b> — ₹186/kg vs PO ₹181.50 on 1,960 kg (₹8,820). Query drafted; needs Accounts.', '<b>Quiet orders</b> — 4 with no factory reply in 48 h; ladders at rung 3–4.', '<b>Overnight</b> — 37 chases, 31 answered, 3 plan dates updated, 0 tasks typed by a person.', '<span class="mono">Reply "1" to open PO 4468 · "2" for the invoice · anything else and I\'ll route it</span>']) + '<div style="display:flex;flex-direction:column;gap:12px">' + card('Delivery', kv([('Channel', 'WhatsApp · +91 98••• 0001'), ('When', '06:00 daily · Sat 08:00'), ('Reads', 'Plans, chats, emails, GRNs'), ('Escalations', 'Rung 5 items always included')]), 'owner') + card('Opened & acted', hbars([('Digests sent · 30 d', 100, '30', ''), ('Opened within 1 h', 93, '28', 'g'), ('Replied with a number', 40, '12', ''), ('Led to a decision', 27, '8', 'r')])) + '</div></div>'),
 dict(slug='phone', fill=True, nav='chats', title='Factory side · on the phone', crumb='Ganesh · Koso Tex print unit · 09:41',
  caption='Factories don\'t log in to anything. They reply on WhatsApp, in Hinglish, with a date — and that reply moves the plan.',
  body='<div class="row top" style="gap:32px">' + phone('WhatsApp', 'Arasu Knits · business', '<div class="bub" style="max-width:92%">Ganesh, print end for 588MC was due today (02 Oct). Kya date de sakte ho — aaj ya kal?<div class="m">09:00 · Arasu Knits</div></div><div class="bub me" style="max-width:92%">Machine issue tha sir, 06 Oct tak ho jayega<div class="m">09:38</div></div><div class="bub" style="max-width:92%">Noted — 06 Oct. Sewing starts 07 Oct; ETD holds. Please send one WIP photo by evening.<div class="m">09:38 · auto-reply</div></div><div class="bub me" style="max-width:92%">📷 Photo<div class="m">09:41</div></div><div class="bub sys">Date captured: print end 06 Oct · plan updated · photo attached to stage</div>') + card('What that one reply did', timeline([('"06 Oct" read from the message', '09:38 · confidence 0.94', 'on'), ('Print stage re-planned; sewing start moved', '09:38', 'on'), ('Ladder stopped for this stage', 'a date was given', 'on'), ('Meena notified: decision needed (accept or push)', '09:38 · in Today', 'on'), ('WIP photo filed against the stage', '09:41', 'on'), ('If 06 Oct slips: ladder restarts at +4 h', 'automatic', 'cur')]), 'no one logged in', 'style="max-width:560px"') + '</div>'),
]
